/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActionOutputConditionFilter2 } from './actionOutputConditionFilter2';
export class ActionOutputCondition {
    'type': ActionOutputCondition.TypeEnum | 'action-output';
    'outputConfigId': number;
    'field': string;
    'filter': ActionOutputConditionFilter2;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ActionOutputCondition.TypeEnum"
        },
        {
            "name": "outputConfigId",
            "baseName": "output_config_id",
            "type": "number"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ActionOutputConditionFilter2"
        }    ];

    static getAttributeTypeMap() {
        return ActionOutputCondition.attributeTypeMap;
    }
}

export namespace ActionOutputCondition {
    export enum TypeEnum {
        ActionOutput = <any> 'action-output'
    }
}
