/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AgeGateProperties } from './ageGateProperties';
import { AgeGateStyles } from './ageGateStyles';
export class AgeGate {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'type': AgeGate.TypeEnum | 'age_gate';
    'styles'?: AgeGateStyles;
    'properties': AgeGateProperties;
    'displayDevice'?: Array<AgeGate.DisplayDeviceEnum> | Array<'both' | 'desktop' | 'mobile'>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AgeGate.TypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "AgeGateStyles"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "AgeGateProperties"
        },
        {
            "name": "displayDevice",
            "baseName": "display_device",
            "type": "Array<AgeGate.DisplayDeviceEnum>"
        }    ];

    static getAttributeTypeMap() {
        return AgeGate.attributeTypeMap;
    }
}

export namespace AgeGate {
    export enum TypeEnum {
        AgeGate = <any> 'age_gate'
    }
    export enum DisplayDeviceEnum {
        Both = <any> 'both',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
}
