/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InStringArrayFilter } from './inStringArrayFilter';
export class APIMethodFilter {
    'field': APIMethodFilter.FieldEnum | 'method';
    'method': APIMethodFilter.MethodEnum | 'api';
    'filter'?: InStringArrayFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "APIMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "APIMethodFilter.MethodEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "InStringArrayFilter"
        }    ];

    static getAttributeTypeMap() {
        return APIMethodFilter.attributeTypeMap;
    }
}

export namespace APIMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        Api = <any> 'api'
    }
}
