/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class BackInStockDynamicButtonDropShadowStyles {
    'enabled'?: boolean = false;
    'color'?: string = '#000000';
    'blur'?: number = 15;
    'xOffset'?: number = 0;
    'yOffset'?: number = 0;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "blur",
            "baseName": "blur",
            "type": "number"
        },
        {
            "name": "xOffset",
            "baseName": "x_offset",
            "type": "number"
        },
        {
            "name": "yOffset",
            "baseName": "y_offset",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BackInStockDynamicButtonDropShadowStyles.attributeTypeMap;
    }
}

