/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorMessages } from './errorMessages';
export class BackInStockEmailConsentCheckboxProperties {
    'displayDevice'?: Array<BackInStockEmailConsentCheckboxProperties.DisplayDeviceEnum> | Array<'both' | 'desktop' | 'mobile'>;
    'classname'?: string | null;
    'label'?: string | null;
    'showLabel'?: boolean = false;
    'errorMessages'?: ErrorMessages;
    'required'?: boolean = false;
    'propertyName'?: BackInStockEmailConsentCheckboxProperties.PropertyNameEnum | 'opt_in_promotional_email' = BackInStockEmailConsentCheckboxProperties.PropertyNameEnum.OptInPromotionalEmail;
    'checkboxText': string;
    'placeholder'?: BackInStockEmailConsentCheckboxProperties.PlaceholderEnum | 'null';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayDevice",
            "baseName": "display_device",
            "type": "Array<BackInStockEmailConsentCheckboxProperties.DisplayDeviceEnum>"
        },
        {
            "name": "classname",
            "baseName": "classname",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "showLabel",
            "baseName": "show_label",
            "type": "boolean"
        },
        {
            "name": "errorMessages",
            "baseName": "error_messages",
            "type": "ErrorMessages"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "propertyName",
            "baseName": "property_name",
            "type": "BackInStockEmailConsentCheckboxProperties.PropertyNameEnum"
        },
        {
            "name": "checkboxText",
            "baseName": "checkbox_text",
            "type": "string"
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "BackInStockEmailConsentCheckboxProperties.PlaceholderEnum"
        }    ];

    static getAttributeTypeMap() {
        return BackInStockEmailConsentCheckboxProperties.attributeTypeMap;
    }
}

export namespace BackInStockEmailConsentCheckboxProperties {
    export enum DisplayDeviceEnum {
        Both = <any> 'both',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
    export enum PropertyNameEnum {
        OptInPromotionalEmail = <any> 'opt_in_promotional_email'
    }
    export enum PlaceholderEnum {
        Null = <any> 'null'
    }
}
