/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseStyleProperties } from './baseStyleProperties';
import { BaseStyleStyles } from './baseStyleStyles';
export class BaseStyle {
    'id'?: string | null;
    'styleType': BaseStyle.StyleTypeEnum | 'base-styles';
    'properties': BaseStyleProperties;
    'styles': BaseStyleStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "styleType",
            "baseName": "style_type",
            "type": "BaseStyle.StyleTypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "BaseStyleProperties"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "BaseStyleStyles"
        }    ];

    static getAttributeTypeMap() {
        return BaseStyle.attributeTypeMap;
    }
}

export namespace BaseStyle {
    export enum StyleTypeEnum {
        BaseStyles = <any> 'base-styles'
    }
}
