/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BodyProperties } from './bodyProperties';
import { BodyStyles } from './bodyStyles';
import { SectionV1 } from './sectionV1';
export class Body {
    'id'?: string | null;
    'properties': BodyProperties;
    'styles': BodyStyles;
    'sections'?: Array<SectionV1> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "BodyProperties"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "BodyStyles"
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<SectionV1>"
        }    ];

    static getAttributeTypeMap() {
        return Body.attributeTypeMap;
    }
}

