/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ButtonBlockProperties } from './buttonBlockProperties';
import { ButtonBlockStyles } from './buttonBlockStyles';
import { DisplayOptions } from './displayOptions';
export class ButtonBlockData {
    'content': string | null;
    'properties': ButtonBlockProperties;
    'displayOptions': DisplayOptions;
    'styles': ButtonBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "ButtonBlockProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "ButtonBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return ButtonBlockData.attributeTypeMap;
    }
}

