/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ButtonBlockV0 {
    'contentType': ButtonBlockV0.ContentTypeEnum | 'block';
    'type': ButtonBlockV0.TypeEnum | 'button';
    'data': any | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "ButtonBlockV0.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ButtonBlockV0.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return ButtonBlockV0.attributeTypeMap;
    }
}

export namespace ButtonBlockV0 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Button = <any> 'button'
    }
}
