/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ButtonBlockData } from './buttonBlockData';
export class ButtonBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': ButtonBlockV1.ContentTypeEnum | 'block';
    'type': ButtonBlockV1.TypeEnum | 'button';
    'data': ButtonBlockData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "ButtonBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ButtonBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ButtonBlockData"
        }    ];

    static getAttributeTypeMap() {
        return ButtonBlockV1.attributeTypeMap;
    }
}

export namespace ButtonBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Button = <any> 'button'
    }
}
