/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignMessageResponseObjectResourceRelationshipsCampaign } from './campaignMessageResponseObjectResourceRelationshipsCampaign';
import { CampaignMessageResponseObjectResourceRelationshipsImage } from './campaignMessageResponseObjectResourceRelationshipsImage';
import { CampaignMessageResponseObjectResourceRelationshipsTemplate } from './campaignMessageResponseObjectResourceRelationshipsTemplate';
export class CampaignMessageResponseObjectResourceRelationships {
    'campaign'?: CampaignMessageResponseObjectResourceRelationshipsCampaign;
    'template'?: CampaignMessageResponseObjectResourceRelationshipsTemplate;
    'image'?: CampaignMessageResponseObjectResourceRelationshipsImage;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaign",
            "baseName": "campaign",
            "type": "CampaignMessageResponseObjectResourceRelationshipsCampaign"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "CampaignMessageResponseObjectResourceRelationshipsTemplate"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "CampaignMessageResponseObjectResourceRelationshipsImage"
        }    ];

    static getAttributeTypeMap() {
        return CampaignMessageResponseObjectResourceRelationships.attributeTypeMap;
    }
}

