/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignResponseObjectResourceRelationshipsCampaignMessages } from './campaignResponseObjectResourceRelationshipsCampaignMessages';
import { FlowResponseObjectResourceRelationshipsTags } from './flowResponseObjectResourceRelationshipsTags';
export class CampaignResponseObjectResourceRelationships {
    'campaignMessages'?: CampaignResponseObjectResourceRelationshipsCampaignMessages;
    'tags'?: FlowResponseObjectResourceRelationshipsTags;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignMessages",
            "baseName": "campaign-messages",
            "type": "CampaignResponseObjectResourceRelationshipsCampaignMessages"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "FlowResponseObjectResourceRelationshipsTags"
        }    ];

    static getAttributeTypeMap() {
        return CampaignResponseObjectResourceRelationships.attributeTypeMap;
    }
}

