/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class CarrierDeactivationMethodFilter {
    'field': CarrierDeactivationMethodFilter.FieldEnum | 'method';
    'method': CarrierDeactivationMethodFilter.MethodEnum | 'carrier_deactivation';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "CarrierDeactivationMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "CarrierDeactivationMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return CarrierDeactivationMethodFilter.attributeTypeMap;
    }
}

export namespace CarrierDeactivationMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        CarrierDeactivation = <any> 'carrier_deactivation'
    }
}
