/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogVariantDeleteJobResponseObjectResourceRelationshipsVariantsDataInner } from './catalogVariantDeleteJobResponseObjectResourceRelationshipsVariantsDataInner';
import { RelationshipLinks } from './relationshipLinks';
export class CatalogVariantDeleteJobResponseObjectResourceRelationshipsVariants {
    'data'?: Array<CatalogVariantDeleteJobResponseObjectResourceRelationshipsVariantsDataInner>;
    'links'?: RelationshipLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<CatalogVariantDeleteJobResponseObjectResourceRelationshipsVariantsDataInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "RelationshipLinks"
        }    ];

    static getAttributeTypeMap() {
        return CatalogVariantDeleteJobResponseObjectResourceRelationshipsVariants.attributeTypeMap;
    }
}

