/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogCategoryDeleteJobResponseObjectResourceRelationshipsCategories } from './catalogCategoryDeleteJobResponseObjectResourceRelationshipsCategories';
export class CatalogCategoryDeleteJobResponseObjectResourceRelationships {
    'categories'?: CatalogCategoryDeleteJobResponseObjectResourceRelationshipsCategories;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categories",
            "baseName": "categories",
            "type": "CatalogCategoryDeleteJobResponseObjectResourceRelationshipsCategories"
        }    ];

    static getAttributeTypeMap() {
        return CatalogCategoryDeleteJobResponseObjectResourceRelationships.attributeTypeMap;
    }
}

