/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChannelProperties } from './channelProperties';
export class Channel {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'type': Channel.TypeEnum | 'channel';
    'properties': ChannelProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Channel.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "ChannelProperties"
        }    ];

    static getAttributeTypeMap() {
        return Channel.attributeTypeMap;
    }
}

export namespace Channel {
    export enum TypeEnum {
        Channel = <any> 'channel'
    }
}
