/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ButtonBlockV1 } from './buttonBlockV1';
import { CouponBlockV1 } from './couponBlockV1';
import { DropShadowBlockV1 } from './dropShadowBlockV1';
import { HTMLBlockV1 } from './hTMLBlockV1';
import { HeaderBlockV1 } from './headerBlockV1';
import { HorizontalRuleBlockV1 } from './horizontalRuleBlockV1';
import { ImageBlockV1 } from './imageBlockV1';
import { ProductBlockV1 } from './productBlockV1';
import { ReviewBlockV1 } from './reviewBlockV1';
import { SocialBlockV1 } from './socialBlockV1';
import { SpacerBlockV1 } from './spacerBlockV1';
import { SplitBlockV1 } from './splitBlockV1';
import { TableBlockV1 } from './tableBlockV1';
import { TableBlockV1SubblocksInner } from './tableBlockV1SubblocksInner';
import { TextBlockV1 } from './textBlockV1';
import { VideoBlockData } from './videoBlockData';
import { VideoBlockV1 } from './videoBlockV1';
export type ColumnV1BlocksInner = ButtonBlockV1 | CouponBlockV1 | DropShadowBlockV1 | HeaderBlockV1 | HorizontalRuleBlockV1 | HTMLBlockV1 | ImageBlockV1 | ProductBlockV1 | ReviewBlockV1 | SocialBlockV1 | SpacerBlockV1 | SplitBlockV1 | TableBlockV1 | TextBlockV1 | VideoBlockV1;
