/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ColumnStyles } from './columnStyles';
import { RowV0 } from './rowV0';
export class ColumnV0 {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'rows'?: Array<RowV0>;
    'styles'?: ColumnStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "rows",
            "baseName": "rows",
            "type": "Array<RowV0>"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "ColumnStyles"
        }    ];

    static getAttributeTypeMap() {
        return ColumnV0.attributeTypeMap;
    }
}

