/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConstantContactIntegrationFilter } from './constantContactIntegrationFilter';
export class ConstantContactIntegrationMethodFilter {
    'field': ConstantContactIntegrationMethodFilter.FieldEnum | 'method';
    'method': ConstantContactIntegrationMethodFilter.MethodEnum | 'integration';
    'filter': ConstantContactIntegrationFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ConstantContactIntegrationMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ConstantContactIntegrationMethodFilter.MethodEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ConstantContactIntegrationFilter"
        }    ];

    static getAttributeTypeMap() {
        return ConstantContactIntegrationMethodFilter.attributeTypeMap;
    }
}

export namespace ConstantContactIntegrationMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        Integration = <any> 'integration'
    }
}
