/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponBlockData } from './couponBlockData';
export class CouponBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': CouponBlockV1.ContentTypeEnum | 'block';
    'type': CouponBlockV1.TypeEnum | 'coupon';
    'data': CouponBlockData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "CouponBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CouponBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CouponBlockData"
        }    ];

    static getAttributeTypeMap() {
        return CouponBlockV1.attributeTypeMap;
    }
}

export namespace CouponBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Coupon = <any> 'coupon'
    }
}
