/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BorderStyle } from './borderStyle';
import { Padding } from './padding';
import { TextStyleV0 } from './textStyleV0';
export class CouponStyles {
    'padding'?: Padding;
    'backgroundColor'?: string | null;
    'textStyles'?: TextStyleV0;
    'borderStyles'?: BorderStyle;
    'couponBackgroundColor'?: string | null = '#EEEEEE';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "padding",
            "baseName": "padding",
            "type": "Padding"
        },
        {
            "name": "backgroundColor",
            "baseName": "background_color",
            "type": "string"
        },
        {
            "name": "textStyles",
            "baseName": "text_styles",
            "type": "TextStyleV0"
        },
        {
            "name": "borderStyles",
            "baseName": "border_styles",
            "type": "BorderStyle"
        },
        {
            "name": "couponBackgroundColor",
            "baseName": "coupon_background_color",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CouponStyles.attributeTypeMap;
    }
}

