/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class CouponBlockStyles {
    'backgroundColor'?: string | null;
    'blockBackgroundColor'?: string | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    'borderColor'?: string | null;
    'borderRadius'?: number | null;
    /**
    * Border style.
    */
    'borderStyle'?: CouponBlockStyles.BorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'borderWidth'?: number | null;
    'color'?: string | null;
    'fontFamily'?: string | null;
    'fontSize'?: number | null;
    /**
    * Font style.
    */
    'fontStyle'?: CouponBlockStyles.FontStyleEnum | 'italic' | 'normal' | null;
    'fontWeight'?: string | null;
    'headerFontFamily'?: string | null;
    'headerFontSize'?: number | null;
    'headerPaddingBottom'?: number | null;
    'headerPaddingLeft'?: number | null;
    'headerPaddingRight'?: number | null;
    'headerPaddingTop'?: number | null;
    'innerPaddingBottom'?: number | null;
    'innerPaddingLeft'?: number | null;
    'innerPaddingRight'?: number | null;
    'innerPaddingTop'?: number | null;
    'letterSpacing'?: number | null;
    'mobileStretchContent'?: boolean | null;
    'stretch'?: boolean | null;
    /**
    * Text Alignment.
    */
    'textAlign'?: CouponBlockStyles.TextAlignEnum | 'center' | 'left' | 'right' | null;
    'textDecoration'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "backgroundColor",
            "baseName": "background_color",
            "type": "string"
        },
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "borderColor",
            "baseName": "border_color",
            "type": "string"
        },
        {
            "name": "borderRadius",
            "baseName": "border_radius",
            "type": "number"
        },
        {
            "name": "borderStyle",
            "baseName": "border_style",
            "type": "CouponBlockStyles.BorderStyleEnum"
        },
        {
            "name": "borderWidth",
            "baseName": "border_width",
            "type": "number"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "fontFamily",
            "baseName": "font_family",
            "type": "string"
        },
        {
            "name": "fontSize",
            "baseName": "font_size",
            "type": "number"
        },
        {
            "name": "fontStyle",
            "baseName": "font_style",
            "type": "CouponBlockStyles.FontStyleEnum"
        },
        {
            "name": "fontWeight",
            "baseName": "font_weight",
            "type": "string"
        },
        {
            "name": "headerFontFamily",
            "baseName": "header_font_family",
            "type": "string"
        },
        {
            "name": "headerFontSize",
            "baseName": "header_font_size",
            "type": "number"
        },
        {
            "name": "headerPaddingBottom",
            "baseName": "header_padding_bottom",
            "type": "number"
        },
        {
            "name": "headerPaddingLeft",
            "baseName": "header_padding_left",
            "type": "number"
        },
        {
            "name": "headerPaddingRight",
            "baseName": "header_padding_right",
            "type": "number"
        },
        {
            "name": "headerPaddingTop",
            "baseName": "header_padding_top",
            "type": "number"
        },
        {
            "name": "innerPaddingBottom",
            "baseName": "inner_padding_bottom",
            "type": "number"
        },
        {
            "name": "innerPaddingLeft",
            "baseName": "inner_padding_left",
            "type": "number"
        },
        {
            "name": "innerPaddingRight",
            "baseName": "inner_padding_right",
            "type": "number"
        },
        {
            "name": "innerPaddingTop",
            "baseName": "inner_padding_top",
            "type": "number"
        },
        {
            "name": "letterSpacing",
            "baseName": "letter_spacing",
            "type": "number"
        },
        {
            "name": "mobileStretchContent",
            "baseName": "mobile_stretch_content",
            "type": "boolean"
        },
        {
            "name": "stretch",
            "baseName": "stretch",
            "type": "boolean"
        },
        {
            "name": "textAlign",
            "baseName": "text_align",
            "type": "CouponBlockStyles.TextAlignEnum"
        },
        {
            "name": "textDecoration",
            "baseName": "text_decoration",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CouponBlockStyles.attributeTypeMap;
    }
}

export namespace CouponBlockStyles {
    export enum BorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum FontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum TextAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
}
