/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class CouponBlockProperties {
    'couponId'?: string | null;
    'coupon'?: string | null;
    'headerEnabled'?: boolean | null;
    'href'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "couponId",
            "baseName": "coupon_id",
            "type": "string"
        },
        {
            "name": "coupon",
            "baseName": "coupon",
            "type": "string"
        },
        {
            "name": "headerEnabled",
            "baseName": "header_enabled",
            "type": "boolean"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CouponBlockProperties.attributeTypeMap;
    }
}

