/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponBlockProperties } from './couponBlockProperties';
import { CouponBlockStyles } from './couponBlockStyles';
import { DisplayOptions } from './displayOptions';
export class CouponBlockData {
    'content': string;
    'properties': CouponBlockProperties;
    'displayOptions': DisplayOptions;
    'styles': CouponBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "CouponBlockProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "CouponBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return CouponBlockData.attributeTypeMap;
    }
}

