/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomObjectPropertyConditionFilter } from './customObjectPropertyConditionFilter';
import { CustomObjectPropertyEnum } from './customObjectPropertyEnum';
export class CustomObjectPropertyCondition {
    'type': CustomObjectPropertyEnum | 'custom-object-property';
    'customObjectLabel': string;
    'field': string;
    'filter': CustomObjectPropertyConditionFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CustomObjectPropertyEnum"
        },
        {
            "name": "customObjectLabel",
            "baseName": "custom_object_label",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "CustomObjectPropertyConditionFilter"
        }    ];

    static getAttributeTypeMap() {
        return CustomObjectPropertyCondition.attributeTypeMap;
    }
}

export namespace CustomObjectPropertyCondition {
}
