/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EqualsStringFilter } from './equalsStringFilter';
export class CustomSourceFilter {
    'field': CustomSourceFilter.FieldEnum | 'custom_source';
    'filter': EqualsStringFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "CustomSourceFilter.FieldEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "EqualsStringFilter"
        }    ];

    static getAttributeTypeMap() {
        return CustomSourceFilter.attributeTypeMap;
    }
}

export namespace CustomSourceFilter {
    export enum FieldEnum {
        CustomSource = <any> 'custom_source'
    }
}
