/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataWarehouseImportEnum } from './dataWarehouseImportEnum';
import { MethodEnum } from './methodEnum';
export class DataWarehouseImportMethodFilter {
    'field': MethodEnum | 'method';
    'method': DataWarehouseImportEnum | 'data_warehouse_import';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "MethodEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "DataWarehouseImportEnum"
        }    ];

    static getAttributeTypeMap() {
        return DataWarehouseImportMethodFilter.attributeTypeMap;
    }
}

export namespace DataWarehouseImportMethodFilter {
}
