/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class DataWarehouseImportMethodFilter {
    'field': DataWarehouseImportMethodFilter.FieldEnum | 'method';
    'method': DataWarehouseImportMethodFilter.MethodEnum | 'data_warehouse_import';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "DataWarehouseImportMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "DataWarehouseImportMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return DataWarehouseImportMethodFilter.attributeTypeMap;
    }
}

export namespace DataWarehouseImportMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        DataWarehouseImport = <any> 'data_warehouse_import'
    }
}
