/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class DataSourceCreateQueryResourceObjectAttributes {
    /**
    * The title of the data source. Must be between 1 and 255 characters and unique within the namespace.
    */
    'title': string;
    /**
    * Visibility of data source.
    */
    'visibility'?: DataSourceCreateQueryResourceObjectAttributes.VisibilityEnum | 'private' | 'shared' | null = DataSourceCreateQueryResourceObjectAttributes.VisibilityEnum.Private;
    'description'?: string | null = '';
    /**
    * The namespace of the data source.
    */
    'namespace'?: string | null = 'custom-objects';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "DataSourceCreateQueryResourceObjectAttributes.VisibilityEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataSourceCreateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

export namespace DataSourceCreateQueryResourceObjectAttributes {
    export enum VisibilityEnum {
        Private = <any> 'private',
        Shared = <any> 'shared'
    }
}
