/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DelayProperties } from './delayProperties';
export class Delay {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'type': Delay.TypeEnum | 'delay';
    'properties'?: DelayProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Delay.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "DelayProperties"
        }    ];

    static getAttributeTypeMap() {
        return Delay.attributeTypeMap;
    }
}

export namespace Delay {
    export enum TypeEnum {
        Delay = <any> 'delay'
    }
}
