/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContentRepeatV1 } from './contentRepeatV1';
import { Visibility } from './visibility';
export class DisplayOptions {
    /**
    * Show on.
    */
    'showOn'?: DisplayOptions.ShowOnEnum | 'all' | 'desktop' | 'mobile' | null;
    'contentRepeat'?: ContentRepeatV1;
    'visibility'?: Visibility;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "showOn",
            "baseName": "show_on",
            "type": "DisplayOptions.ShowOnEnum"
        },
        {
            "name": "contentRepeat",
            "baseName": "content_repeat",
            "type": "ContentRepeatV1"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "Visibility"
        }    ];

    static getAttributeTypeMap() {
        return DisplayOptions.attributeTypeMap;
    }
}

export namespace DisplayOptions {
    export enum ShowOnEnum {
        All = <any> 'all',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
}
