/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DropShadowBlockData } from './dropShadowBlockData';
export class DropShadowBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': DropShadowBlockV1.ContentTypeEnum | 'block';
    'type': DropShadowBlockV1.TypeEnum | 'drop_shadow';
    'data': DropShadowBlockData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "DropShadowBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DropShadowBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DropShadowBlockData"
        }    ];

    static getAttributeTypeMap() {
        return DropShadowBlockV1.attributeTypeMap;
    }
}

export namespace DropShadowBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        DropShadow = <any> 'drop_shadow'
    }
}
