/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DropdownProperties } from './dropdownProperties';
import { DropdownStyles } from './dropdownStyles';
export class Dropdown {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'type': Dropdown.TypeEnum | 'dropdown';
    'styles'?: DropdownStyles;
    'properties': DropdownProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Dropdown.TypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "DropdownStyles"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "DropdownProperties"
        }    ];

    static getAttributeTypeMap() {
        return Dropdown.attributeTypeMap;
    }
}

export namespace Dropdown {
    export enum TypeEnum {
        Dropdown = <any> 'dropdown'
    }
}
