/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContentRepeatV1 } from './contentRepeatV1';
export class DynamicTableBlockProperties {
    'dynamic': boolean;
    'numColumns'?: number | null;
    'rowContentRepeat'?: ContentRepeatV1;
    'showHeaders'?: boolean | null;
    'showFallbackContent'?: boolean | null;
    'showStaticRow'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dynamic",
            "baseName": "dynamic",
            "type": "boolean"
        },
        {
            "name": "numColumns",
            "baseName": "num_columns",
            "type": "number"
        },
        {
            "name": "rowContentRepeat",
            "baseName": "row_content_repeat",
            "type": "ContentRepeatV1"
        },
        {
            "name": "showHeaders",
            "baseName": "show_headers",
            "type": "boolean"
        },
        {
            "name": "showFallbackContent",
            "baseName": "show_fallback_content",
            "type": "boolean"
        },
        {
            "name": "showStaticRow",
            "baseName": "show_static_row",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DynamicTableBlockProperties.attributeTypeMap;
    }
}

