/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StatusDateFilterFilter } from './statusDateFilterFilter';
export class EffectiveDateFilter {
    'field': EffectiveDateFilter.FieldEnum | 'effective_date';
    'filter': StatusDateFilterFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "EffectiveDateFilter.FieldEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "StatusDateFilterFilter"
        }    ];

    static getAttributeTypeMap() {
        return EffectiveDateFilter.attributeTypeMap;
    }
}

export namespace EffectiveDateFilter {
    export enum FieldEnum {
        EffectiveDate = <any> 'effective_date'
    }
}
