/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmailProperties } from './emailProperties';
import { EmailStyles } from './emailStyles';
export class Email {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'type': Email.TypeEnum | 'email';
    'styles'?: EmailStyles;
    'properties': EmailProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Email.TypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "EmailStyles"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "EmailProperties"
        }    ];

    static getAttributeTypeMap() {
        return Email.attributeTypeMap;
    }
}

export namespace Email {
    export enum TypeEnum {
        Email = <any> 'email'
    }
}
