/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExistenceEnum } from './existenceEnum';
export class ExistenceOperatorExistenceFilter {
    'type': ExistenceEnum | 'existence';
    /**
    * Operators for existence filters.
    */
    'operator': ExistenceOperatorExistenceFilter.OperatorEnum | 'is-set' | 'not-set';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ExistenceEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ExistenceOperatorExistenceFilter.OperatorEnum"
        }    ];

    static getAttributeTypeMap() {
        return ExistenceOperatorExistenceFilter.attributeTypeMap;
    }
}

export namespace ExistenceOperatorExistenceFilter {
    export enum OperatorEnum {
        IsSet = <any> 'is-set',
        NotSet = <any> 'not-set'
    }
}
