/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExplicitlyReachableFiltersInner } from './explicitlyReachableFiltersInner';
export class ExplicitlyUnreachable {
    'reachableStatus': ExplicitlyUnreachable.ReachableStatusEnum | 'explicitly_unreachable';
    'filters': Array<ExplicitlyReachableFiltersInner>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reachableStatus",
            "baseName": "reachable_status",
            "type": "ExplicitlyUnreachable.ReachableStatusEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<ExplicitlyReachableFiltersInner>"
        }    ];

    static getAttributeTypeMap() {
        return ExplicitlyUnreachable.attributeTypeMap;
    }
}

export namespace ExplicitlyUnreachable {
    export enum ReachableStatusEnum {
        ExplicitlyUnreachable = <any> 'explicitly_unreachable'
    }
}
