/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class FailedAgeGateMethodFilter {
    'field': FailedAgeGateMethodFilter.FieldEnum | 'method';
    'method': FailedAgeGateMethodFilter.MethodEnum | 'failed_age_gate';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "FailedAgeGateMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "FailedAgeGateMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return FailedAgeGateMethodFilter.attributeTypeMap;
    }
}

export namespace FailedAgeGateMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        FailedAgeGate = <any> 'failed_age_gate'
    }
}
