/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowMessageEncodedResponseObjectResourceRelationshipsFlowAction } from './flowMessageEncodedResponseObjectResourceRelationshipsFlowAction';
import { FlowMessageEncodedResponseObjectResourceRelationshipsTemplate } from './flowMessageEncodedResponseObjectResourceRelationshipsTemplate';
export class FlowMessageEncodedResponseObjectResourceRelationships {
    'flowAction'?: FlowMessageEncodedResponseObjectResourceRelationshipsFlowAction;
    'template'?: FlowMessageEncodedResponseObjectResourceRelationshipsTemplate;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flowAction",
            "baseName": "flow-action",
            "type": "FlowMessageEncodedResponseObjectResourceRelationshipsFlowAction"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "FlowMessageEncodedResponseObjectResourceRelationshipsTemplate"
        }    ];

    static getAttributeTypeMap() {
        return FlowMessageEncodedResponseObjectResourceRelationships.attributeTypeMap;
    }
}

