/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowActionEncodedResponseObjectResourceRelationshipsFlow } from './flowActionEncodedResponseObjectResourceRelationshipsFlow';
import { FlowActionEncodedResponseObjectResourceRelationshipsFlowMessages } from './flowActionEncodedResponseObjectResourceRelationshipsFlowMessages';
export class FlowActionEncodedResponseObjectResourceRelationships {
    'flow'?: FlowActionEncodedResponseObjectResourceRelationshipsFlow;
    'flowMessages'?: FlowActionEncodedResponseObjectResourceRelationshipsFlowMessages;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flow",
            "baseName": "flow",
            "type": "FlowActionEncodedResponseObjectResourceRelationshipsFlow"
        },
        {
            "name": "flowMessages",
            "baseName": "flow-messages",
            "type": "FlowActionEncodedResponseObjectResourceRelationshipsFlowMessages"
        }    ];

    static getAttributeTypeMap() {
        return FlowActionEncodedResponseObjectResourceRelationships.attributeTypeMap;
    }
}

