/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FormResponseObjectResourceRelationshipsFormVersions } from './formResponseObjectResourceRelationshipsFormVersions';
export class FormResponseObjectResourceRelationships {
    'formVersions'?: FormResponseObjectResourceRelationshipsFormVersions;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "formVersions",
            "baseName": "form-versions",
            "type": "FormResponseObjectResourceRelationshipsFormVersions"
        }    ];

    static getAttributeTypeMap() {
        return FormResponseObjectResourceRelationships.attributeTypeMap;
    }
}

