/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponCodeCreateJobResponseObjectResource } from './couponCodeCreateJobResponseObjectResource';
import { CouponCodeResponseObjectResource } from './couponCodeResponseObjectResource';
import { ObjectLinks } from './objectLinks';
export class GetCouponCodeCreateJobResponseCompoundDocument {
    'data': CouponCodeCreateJobResponseObjectResource;
    'included'?: Array<CouponCodeResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "CouponCodeCreateJobResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<CouponCodeResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetCouponCodeCreateJobResponseCompoundDocument.attributeTypeMap;
    }
}

