/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogCategoryCreateJobResponseObjectResource } from './catalogCategoryCreateJobResponseObjectResource';
import { CatalogCategoryResponseObjectResource } from './catalogCategoryResponseObjectResource';
import { ObjectLinks } from './objectLinks';
export class GetCatalogCategoryCreateJobResponseCompoundDocument {
    'data': CatalogCategoryCreateJobResponseObjectResource;
    'included'?: Array<CatalogCategoryResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "CatalogCategoryCreateJobResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<CatalogCategoryResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetCatalogCategoryCreateJobResponseCompoundDocument.attributeTypeMap;
    }
}

