/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogVariantCreateJobResponseObjectResource } from './catalogVariantCreateJobResponseObjectResource';
import { CatalogVariantResponseObjectResource } from './catalogVariantResponseObjectResource';
import { ObjectLinks } from './objectLinks';
export class GetCatalogVariantCreateJobResponseCompoundDocument {
    'data': CatalogVariantCreateJobResponseObjectResource;
    'included'?: Array<CatalogVariantResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "CatalogVariantCreateJobResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<CatalogVariantResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetCatalogVariantCreateJobResponseCompoundDocument.attributeTypeMap;
    }
}

