/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignResponseObjectResource } from './campaignResponseObjectResource';
import { GetCampaignResponseCollectionCompoundDocumentIncludedInner } from './getCampaignResponseCollectionCompoundDocumentIncludedInner';
import { ObjectLinks } from './objectLinks';
export class GetCampaignResponseCompoundDocument {
    'data': CampaignResponseObjectResource;
    'included'?: Array<GetCampaignResponseCollectionCompoundDocumentIncludedInner>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "CampaignResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetCampaignResponseCollectionCompoundDocumentIncludedInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetCampaignResponseCompoundDocument.attributeTypeMap;
    }
}

