/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionLinks } from './collectionLinks';
import { EventResponseObjectResource } from './eventResponseObjectResource';
import { GetEventResponseCollectionCompoundDocumentIncludedInner } from './getEventResponseCollectionCompoundDocumentIncludedInner';
export class GetEventResponseCollectionCompoundDocument {
    'data': Array<EventResponseObjectResource>;
    'links'?: CollectionLinks;
    'included'?: Array<GetEventResponseCollectionCompoundDocumentIncludedInner>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<EventResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "CollectionLinks"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetEventResponseCollectionCompoundDocumentIncludedInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetEventResponseCollectionCompoundDocument.attributeTypeMap;
    }
}

