/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FormEnum } from './formEnum';
import { FormResponseObjectResource } from './formResponseObjectResource';
import { FormResponseObjectResourceAttributes } from './formResponseObjectResourceAttributes';
import { GetFormResponseCollectionDataInnerAllOfRelationships } from './getFormResponseCollectionDataInnerAllOfRelationships';
import { ObjectLinks } from './objectLinks';
export class GetFormResponseCollectionDataInner extends FormResponseObjectResource {
    'relationships'?: GetFormResponseCollectionDataInnerAllOfRelationships;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GetFormResponseCollectionDataInnerAllOfRelationships"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GetFormResponseCollectionDataInner.attributeTypeMap);
    }
}

export namespace GetFormResponseCollectionDataInner {
}
