/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetFlowActionEncodedResponseCompoundDocumentData } from './getFlowActionEncodedResponseCompoundDocumentData';
import { GetFlowActionEncodedResponseCompoundDocumentIncludedInner } from './getFlowActionEncodedResponseCompoundDocumentIncludedInner';
import { ObjectLinks } from './objectLinks';
export class GetFlowActionEncodedResponseCompoundDocument {
    'data': GetFlowActionEncodedResponseCompoundDocumentData;
    'included'?: Array<GetFlowActionEncodedResponseCompoundDocumentIncludedInner>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "GetFlowActionEncodedResponseCompoundDocumentData"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetFlowActionEncodedResponseCompoundDocumentIncludedInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetFlowActionEncodedResponseCompoundDocument.attributeTypeMap;
    }
}

