/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowEnum } from './flowEnum';
import { FlowResponseObjectResource } from './flowResponseObjectResource';
import { FlowResponseObjectResourceAttributes } from './flowResponseObjectResourceAttributes';
import { FlowResponseObjectResourceRelationships } from './flowResponseObjectResourceRelationships';
import { ObjectLinks } from './objectLinks';
import { TagResponseObjectResource } from './tagResponseObjectResource';



    export type GetListListResponseCollectionCompoundDocumentIncludedInner = FlowResponseObjectResource | TagResponseObjectResource

    export class GetListListResponseCollectionCompoundDocumentIncludedInnerHelper {
        static mapping: {[index: string]: any} = {
            "flow": "FlowResponseObjectResource",
            "tag": "TagResponseObjectResource",
        }
        static discriminator: string | undefined = "type";
    }

