/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionLinks } from './collectionLinks';
import { FlowResponseObjectResource } from './flowResponseObjectResource';
import { MetricResponseObjectResource } from './metricResponseObjectResource';
export class GetMetricResponseCollectionCompoundDocument {
    'data': Array<MetricResponseObjectResource>;
    'links'?: CollectionLinks;
    'included'?: Array<FlowResponseObjectResource>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<MetricResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "CollectionLinks"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<FlowResponseObjectResource>"
        }    ];

    static getAttributeTypeMap() {
        return GetMetricResponseCollectionCompoundDocument.attributeTypeMap;
    }
}

