/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowResponseObjectResource } from './flowResponseObjectResource';
import { MetricResponseObjectResource } from './metricResponseObjectResource';
import { ObjectLinks } from './objectLinks';
export class GetMetricResponseCompoundDocument {
    'data': MetricResponseObjectResource;
    'included'?: Array<FlowResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "MetricResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<FlowResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetMetricResponseCompoundDocument.attributeTypeMap;
    }
}

