/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetMappedMetricResponseCollectionCompoundDocumentIncludedInner } from './getMappedMetricResponseCollectionCompoundDocumentIncludedInner';
import { MappedMetricResponseObjectResource } from './mappedMetricResponseObjectResource';
import { ObjectLinks } from './objectLinks';
export class GetMappedMetricResponseCompoundDocument {
    'data': MappedMetricResponseObjectResource;
    'included'?: Array<GetMappedMetricResponseCollectionCompoundDocumentIncludedInner>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "MappedMetricResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetMappedMetricResponseCollectionCompoundDocumentIncludedInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetMappedMetricResponseCompoundDocument.attributeTypeMap;
    }
}

