/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectLinks } from './objectLinks';
import { ProfileResponseObjectResource } from './profileResponseObjectResource';
import { PushTokenResponseObjectResource } from './pushTokenResponseObjectResource';
export class GetPushTokenResponseCompoundDocument {
    'data': PushTokenResponseObjectResource;
    'included'?: Array<ProfileResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "PushTokenResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<ProfileResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetPushTokenResponseCompoundDocument.attributeTypeMap;
    }
}

