/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionLinks } from './collectionLinks';
import { ProfileResponseObjectResource } from './profileResponseObjectResource';
import { PushTokenResponseObjectResource } from './pushTokenResponseObjectResource';
export class GetPushTokenResponseCollectionCompoundDocument {
    'data': Array<PushTokenResponseObjectResource>;
    'links'?: CollectionLinks;
    'included'?: Array<ProfileResponseObjectResource>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<PushTokenResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "CollectionLinks"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<ProfileResponseObjectResource>"
        }    ];

    static getAttributeTypeMap() {
        return GetPushTokenResponseCollectionCompoundDocument.attributeTypeMap;
    }
}

