/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionLinks } from './collectionLinks';
import { GetProfileResponseCollectionCompoundDocumentIncludedInner } from './getProfileResponseCollectionCompoundDocumentIncludedInner';
import { ProfileResponseObjectResourceExtended } from './profileResponseObjectResourceExtended';
export class GetProfileResponseCollectionCompoundDocument {
    'data': Array<ProfileResponseObjectResourceExtended>;
    'links'?: CollectionLinks;
    'included'?: Array<GetProfileResponseCollectionCompoundDocumentIncludedInner>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ProfileResponseObjectResourceExtended>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "CollectionLinks"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetProfileResponseCollectionCompoundDocumentIncludedInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetProfileResponseCollectionCompoundDocument.attributeTypeMap;
    }
}

