/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetListListResponseCollectionCompoundDocumentIncludedInner } from './getListListResponseCollectionCompoundDocumentIncludedInner';
import { ObjectLinks } from './objectLinks';
import { SegmentRetrieveResponseObjectResourceExtended } from './segmentRetrieveResponseObjectResourceExtended';
export class GetSegmentRetrieveResponseCompoundDocument {
    'data': SegmentRetrieveResponseObjectResourceExtended;
    'included'?: Array<GetListListResponseCollectionCompoundDocumentIncludedInner>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "SegmentRetrieveResponseObjectResourceExtended"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetListListResponseCollectionCompoundDocumentIncludedInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetSegmentRetrieveResponseCompoundDocument.attributeTypeMap;
    }
}

