/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectLinks } from './objectLinks';
import { TagGroupResponseObjectResource } from './tagGroupResponseObjectResource';
import { TagResponseObjectResource } from './tagResponseObjectResource';
export class GetTagResponseCompoundDocument {
    'data': TagResponseObjectResource;
    'included'?: Array<TagGroupResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "TagResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<TagGroupResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetTagResponseCompoundDocument.attributeTypeMap;
    }
}

