/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectLinks } from './objectLinks';
import { WebhookResponseObjectResource } from './webhookResponseObjectResource';
import { WebhookTopicResponseObjectResource } from './webhookTopicResponseObjectResource';
export class GetWebhookResponseCompoundDocument {
    'data': WebhookResponseObjectResource;
    'included'?: Array<WebhookTopicResponseObjectResource>;
    'links'?: ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "WebhookResponseObjectResource"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<WebhookTopicResponseObjectResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return GetWebhookResponseCompoundDocument.attributeTypeMap;
    }
}

