/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NumericOperatorNumericFilterValue } from './numericOperatorNumericFilterValue';
export class GreaterThanPositiveNumericFilter {
    'type': GreaterThanPositiveNumericFilter.TypeEnum | 'numeric';
    'operator': GreaterThanPositiveNumericFilter.OperatorEnum | 'greater-than';
    'value': NumericOperatorNumericFilterValue;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GreaterThanPositiveNumericFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "GreaterThanPositiveNumericFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "NumericOperatorNumericFilterValue"
        }    ];

    static getAttributeTypeMap() {
        return GreaterThanPositiveNumericFilter.attributeTypeMap;
    }
}

export namespace GreaterThanPositiveNumericFilter {
    export enum TypeEnum {
        Numeric = <any> 'numeric'
    }
    export enum OperatorEnum {
        GreaterThan = <any> 'greater-than'
    }
}
