/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HasPushMarketing } from './hasPushMarketing';
export class HasPushMarketingConsent {
    'channel': HasPushMarketingConsent.ChannelEnum | 'push';
    'canReceiveMarketing': boolean;
    'consentStatus': HasPushMarketing;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "HasPushMarketingConsent.ChannelEnum"
        },
        {
            "name": "canReceiveMarketing",
            "baseName": "can_receive_marketing",
            "type": "boolean"
        },
        {
            "name": "consentStatus",
            "baseName": "consent_status",
            "type": "HasPushMarketing"
        }    ];

    static getAttributeTypeMap() {
        return HasPushMarketingConsent.attributeTypeMap;
    }
}

export namespace HasPushMarketingConsent {
    export enum ChannelEnum {
        Push = <any> 'push'
    }
}
