/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StatusDateFilter } from './statusDateFilter';
export class HasPushMarketing {
    'subscription': HasPushMarketing.SubscriptionEnum | 'any';
    'filters'?: Array<StatusDateFilter> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "HasPushMarketing.SubscriptionEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<StatusDateFilter>"
        }    ];

    static getAttributeTypeMap() {
        return HasPushMarketing.attributeTypeMap;
    }
}

export namespace HasPushMarketing {
    export enum SubscriptionEnum {
        Any = <any> 'any'
    }
}
