/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BooleanFilter } from './booleanFilter';
import { CheckoutMethodFilter } from './checkoutMethodFilter';
import { FormMethodFilter } from './formMethodFilter';
import { InboundMessageMethodFilter } from './inboundMessageMethodFilter';
import { ManualAddManualMethodFilter } from './manualAddManualMethodFilter';
import { ManualImportManualMethodFilter } from './manualImportManualMethodFilter';
import { PreferencePageMethodFilter } from './preferencePageMethodFilter';
import { SftpMethodFilter } from './sftpMethodFilter';
import { ShopifyIntegrationMethodFilter } from './shopifyIntegrationMethodFilter';
import { StatusDateFilter } from './statusDateFilter';
import { SubscribedSMSIsRcsCapableFilter } from './subscribedSMSIsRcsCapableFilter';
export type HasSMSMarketingSubscribedFiltersInner = StatusDateFilter | FormMethodFilter | ManualImportManualMethodFilter | ManualAddManualMethodFilter | CheckoutMethodFilter | InboundMessageMethodFilter | PreferencePageMethodFilter | SftpMethodFilter | ShopifyIntegrationMethodFilter | SubscribedSMSIsRcsCapableFilter;
