/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { HeaderBlockStyles } from './headerBlockStyles';
export class HeaderBlockData {
    'displayOptions': DisplayOptions;
    'styles': HeaderBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "HeaderBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return HeaderBlockData.attributeTypeMap;
    }
}

