/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class HeaderBlockStyles {
    'blockBackgroundColor'?: string | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    'borderColor'?: string | null;
    'borderRadius'?: number | null;
    /**
    * Border style.
    */
    'borderStyle'?: HeaderBlockStyles.BorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'borderWidth'?: number | null;
    'color'?: string | null;
    /**
    * Header block desktop layout.
    */
    'desktopLayout'?: HeaderBlockStyles.DesktopLayoutEnum | 'centered' | 'inline' | 'links' | 'stacked' | null;
    'fontFamily'?: string | null;
    'fontSize'?: number | null;
    /**
    * Font style.
    */
    'fontStyle'?: HeaderBlockStyles.FontStyleEnum | 'italic' | 'normal' | null;
    'fontWeight'?: string | null;
    'innerPaddingBottom'?: number | null;
    'innerPaddingLeft'?: number | null;
    'innerPaddingRight'?: number | null;
    'innerPaddingTop'?: number | null;
    /**
    * Text Alignment.
    */
    'itemAlign'?: HeaderBlockStyles.ItemAlignEnum | 'center' | 'left' | 'right' | null;
    'itemSpacing'?: number | null;
    /**
    * Header block item spacing type.
    */
    'itemSpacingType'?: HeaderBlockStyles.ItemSpacingTypeEnum | 'auto' | 'manual' | null;
    'letterSpacing'?: number | null;
    /**
    * Text Alignment.
    */
    'logoAlign'?: HeaderBlockStyles.LogoAlignEnum | 'center' | 'left' | 'right' | null;
    'logoLinkSpacing'?: number | null;
    /**
    * Header block mobile layout.
    */
    'mobileLayout'?: HeaderBlockStyles.MobileLayoutEnum | 'inline' | 'links' | 'links-stacked' | 'logo-stacked' | 'stacked' | null;
    'mobileSpacing'?: number | null;
    'mobileWrap'?: boolean | null;
    'textDecoration'?: string | null;
    /**
    * Vertical alignment.
    */
    'verticalAlign'?: HeaderBlockStyles.VerticalAlignEnum | 'baseline' | 'bottom' | 'middle' | 'top' | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "borderColor",
            "baseName": "border_color",
            "type": "string"
        },
        {
            "name": "borderRadius",
            "baseName": "border_radius",
            "type": "number"
        },
        {
            "name": "borderStyle",
            "baseName": "border_style",
            "type": "HeaderBlockStyles.BorderStyleEnum"
        },
        {
            "name": "borderWidth",
            "baseName": "border_width",
            "type": "number"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "desktopLayout",
            "baseName": "desktop_layout",
            "type": "HeaderBlockStyles.DesktopLayoutEnum"
        },
        {
            "name": "fontFamily",
            "baseName": "font_family",
            "type": "string"
        },
        {
            "name": "fontSize",
            "baseName": "font_size",
            "type": "number"
        },
        {
            "name": "fontStyle",
            "baseName": "font_style",
            "type": "HeaderBlockStyles.FontStyleEnum"
        },
        {
            "name": "fontWeight",
            "baseName": "font_weight",
            "type": "string"
        },
        {
            "name": "innerPaddingBottom",
            "baseName": "inner_padding_bottom",
            "type": "number"
        },
        {
            "name": "innerPaddingLeft",
            "baseName": "inner_padding_left",
            "type": "number"
        },
        {
            "name": "innerPaddingRight",
            "baseName": "inner_padding_right",
            "type": "number"
        },
        {
            "name": "innerPaddingTop",
            "baseName": "inner_padding_top",
            "type": "number"
        },
        {
            "name": "itemAlign",
            "baseName": "item_align",
            "type": "HeaderBlockStyles.ItemAlignEnum"
        },
        {
            "name": "itemSpacing",
            "baseName": "item_spacing",
            "type": "number"
        },
        {
            "name": "itemSpacingType",
            "baseName": "item_spacing_type",
            "type": "HeaderBlockStyles.ItemSpacingTypeEnum"
        },
        {
            "name": "letterSpacing",
            "baseName": "letter_spacing",
            "type": "number"
        },
        {
            "name": "logoAlign",
            "baseName": "logo_align",
            "type": "HeaderBlockStyles.LogoAlignEnum"
        },
        {
            "name": "logoLinkSpacing",
            "baseName": "logo_link_spacing",
            "type": "number"
        },
        {
            "name": "mobileLayout",
            "baseName": "mobile_layout",
            "type": "HeaderBlockStyles.MobileLayoutEnum"
        },
        {
            "name": "mobileSpacing",
            "baseName": "mobile_spacing",
            "type": "number"
        },
        {
            "name": "mobileWrap",
            "baseName": "mobile_wrap",
            "type": "boolean"
        },
        {
            "name": "textDecoration",
            "baseName": "text_decoration",
            "type": "string"
        },
        {
            "name": "verticalAlign",
            "baseName": "vertical_align",
            "type": "HeaderBlockStyles.VerticalAlignEnum"
        }    ];

    static getAttributeTypeMap() {
        return HeaderBlockStyles.attributeTypeMap;
    }
}

export namespace HeaderBlockStyles {
    export enum BorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum DesktopLayoutEnum {
        Centered = <any> 'centered',
        Inline = <any> 'inline',
        Links = <any> 'links',
        Stacked = <any> 'stacked'
    }
    export enum FontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum ItemAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum ItemSpacingTypeEnum {
        Auto = <any> 'auto',
        Manual = <any> 'manual'
    }
    export enum LogoAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum MobileLayoutEnum {
        Inline = <any> 'inline',
        Links = <any> 'links',
        LinksStacked = <any> 'links-stacked',
        LogoStacked = <any> 'logo-stacked',
        Stacked = <any> 'stacked'
    }
    export enum VerticalAlignEnum {
        Baseline = <any> 'baseline',
        Bottom = <any> 'bottom',
        Middle = <any> 'middle',
        Top = <any> 'top'
    }
}
