/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HeadingStyleStyles } from './headingStyleStyles';
export class Heading3Style {
    'id'?: string | null;
    'styleType': Heading3Style.StyleTypeEnum | 'heading-3-styles';
    'styles': HeadingStyleStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "styleType",
            "baseName": "style_type",
            "type": "Heading3Style.StyleTypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "HeadingStyleStyles"
        }    ];

    static getAttributeTypeMap() {
        return Heading3Style.attributeTypeMap;
    }
}

export namespace Heading3Style {
    export enum StyleTypeEnum {
        Heading3Styles = <any> 'heading-3-styles'
    }
}
