/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class HorizontalRuleBlockStyles {
    'blockBackgroundColor'?: string | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    'borderColor'?: string | null;
    /**
    * Border style.
    */
    'borderStyle'?: HorizontalRuleBlockStyles.BorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'borderWidth'?: number | null;
    'mobileStretchContent'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "borderColor",
            "baseName": "border_color",
            "type": "string"
        },
        {
            "name": "borderStyle",
            "baseName": "border_style",
            "type": "HorizontalRuleBlockStyles.BorderStyleEnum"
        },
        {
            "name": "borderWidth",
            "baseName": "border_width",
            "type": "number"
        },
        {
            "name": "mobileStretchContent",
            "baseName": "mobile_stretch_content",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return HorizontalRuleBlockStyles.attributeTypeMap;
    }
}

export namespace HorizontalRuleBlockStyles {
    export enum BorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
}
