/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HorizontalRuleBlockData } from './horizontalRuleBlockData';
export class HorizontalRuleBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': HorizontalRuleBlockV1.ContentTypeEnum | 'block';
    'type': HorizontalRuleBlockV1.TypeEnum | 'horizontal_rule';
    'data': HorizontalRuleBlockData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "HorizontalRuleBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "HorizontalRuleBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "HorizontalRuleBlockData"
        }    ];

    static getAttributeTypeMap() {
        return HorizontalRuleBlockV1.attributeTypeMap;
    }
}

export namespace HorizontalRuleBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        HorizontalRule = <any> 'horizontal_rule'
    }
}
