/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HTMLBlockDataV0 } from './hTMLBlockDataV0';
export class HTMLBlockV0 {
    'contentType': HTMLBlockV0.ContentTypeEnum | 'block';
    'type': HTMLBlockV0.TypeEnum | 'html';
    'data': HTMLBlockDataV0;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "HTMLBlockV0.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "HTMLBlockV0.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "HTMLBlockDataV0"
        }    ];

    static getAttributeTypeMap() {
        return HTMLBlockV0.attributeTypeMap;
    }
}

export namespace HTMLBlockV0 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Html = <any> 'html'
    }
}
