/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HTMLBlockDataV1 } from './hTMLBlockDataV1';
export class HTMLBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': HTMLBlockV1.ContentTypeEnum | 'block';
    'type': HTMLBlockV1.TypeEnum | 'html';
    'data': HTMLBlockDataV1;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "HTMLBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "HTMLBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "HTMLBlockDataV1"
        }    ];

    static getAttributeTypeMap() {
        return HTMLBlockV1.attributeTypeMap;
    }
}

export namespace HTMLBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Html = <any> 'html'
    }
}
