/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class IdentifiedProfiles {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'properties'?: object;
    'type': IdentifiedProfiles.TypeEnum | 'identified_profiles';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "object"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IdentifiedProfiles.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return IdentifiedProfiles.attributeTypeMap;
    }
}

export namespace IdentifiedProfiles {
    export enum TypeEnum {
        IdentifiedProfiles = <any> 'identified_profiles'
    }
}
