/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ImageBlockData } from './imageBlockData';
export class ImageBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': ImageBlockV1.ContentTypeEnum | 'block';
    'type': ImageBlockV1.TypeEnum | 'image';
    'data': ImageBlockData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "ImageBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ImageBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ImageBlockData"
        }    ];

    static getAttributeTypeMap() {
        return ImageBlockV1.attributeTypeMap;
    }
}

export namespace ImageBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Image = <any> 'image'
    }
}
