/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { ImageBlockDataProperties } from './imageBlockDataProperties';
import { ImageBlockStyles } from './imageBlockStyles';
export class ImageBlockData {
    'properties': ImageBlockDataProperties;
    'displayOptions': DisplayOptions;
    'styles': ImageBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "ImageBlockDataProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "ImageBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return ImageBlockData.attributeTypeMap;
    }
}

