/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DynamicImageBlockProperties } from './dynamicImageBlockProperties';
import { ImageBlockCroppingProperties } from './imageBlockCroppingProperties';
import { StaticImageBlockProperties } from './staticImageBlockProperties';
export type ImageBlockDataProperties = StaticImageBlockProperties | DynamicImageBlockProperties;
