/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ImageBlockV0 {
    'contentType': ImageBlockV0.ContentTypeEnum | 'block';
    'type': ImageBlockV0.TypeEnum | 'image';
    'data': any | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "ImageBlockV0.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ImageBlockV0.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return ImageBlockV0.attributeTypeMap;
    }
}

export namespace ImageBlockV0 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Image = <any> 'image'
    }
}
