/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ImageBlockCroppingProperties {
    /**
    * Aspect ratio options.
    */
    'aspectRatio'?: ImageBlockCroppingProperties.AspectRatioEnum | '16:9' | '1:1' | '2:3' | '3:4' | '4:3' | 'circle' | 'custom' | 'original' | null;
    'assetId'?: string | null;
    'height'?: number | null;
    'src'?: string | null;
    'width'?: number | null;
    'x'?: number | null;
    'y'?: number | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aspectRatio",
            "baseName": "aspect_ratio",
            "type": "ImageBlockCroppingProperties.AspectRatioEnum"
        },
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "src",
            "baseName": "src",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "x",
            "baseName": "x",
            "type": "number"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ImageBlockCroppingProperties.attributeTypeMap;
    }
}

export namespace ImageBlockCroppingProperties {
    export enum AspectRatioEnum {
        _169 = <any> '16:9',
        _11 = <any> '1:1',
        _23 = <any> '2:3',
        _34 = <any> '3:4',
        _43 = <any> '4:3',
        Circle = <any> 'circle',
        Custom = <any> 'custom',
        Original = <any> 'original'
    }
}
