/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ImplicitlyUnreachable {
    'reachableStatus': ImplicitlyUnreachable.ReachableStatusEnum | 'implicitly_unreachable';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reachableStatus",
            "baseName": "reachable_status",
            "type": "ImplicitlyUnreachable.ReachableStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ImplicitlyUnreachable.attributeTypeMap;
    }
}

export namespace ImplicitlyUnreachable {
    export enum ReachableStatusEnum {
        ImplicitlyUnreachable = <any> 'implicitly_unreachable'
    }
}
