/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InternalScheduledReportBuilderReportData } from './internalScheduledReportBuilderReportData';
import { InternalScheduledReportData } from './internalScheduledReportData';
import { InternalTrackEventData } from './internalTrackEventData';
import { InternalUnknownServiceData } from './internalUnknownServiceData';
export type InternalServiceActionDataServiceConfiguration = InternalScheduledReportData | InternalTrackEventData | InternalScheduledReportBuilderReportData | InternalUnknownServiceData;
