/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NumericEnum } from './numericEnum';
export class IntegerFilter {
    'type': NumericEnum | 'numeric';
    /**
    * Operators for numeric filters.
    */
    'operator': IntegerFilter.OperatorEnum | 'equals' | 'greater-than' | 'greater-than-or-equal' | 'less-than' | 'less-than-or-equal' | 'not-equals';
    'value': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "NumericEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "IntegerFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IntegerFilter.attributeTypeMap;
    }
}

export namespace IntegerFilter {
    export enum OperatorEnum {
        Equals = <any> 'equals',
        GreaterThan = <any> 'greater-than',
        GreaterThanOrEqual = <any> 'greater-than-or-equal',
        LessThan = <any> 'less-than',
        LessThanOrEqual = <any> 'less-than-or-equal',
        NotEquals = <any> 'not-equals'
    }
}
