/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InternalServiceActionDataServiceConfiguration } from './internalServiceActionDataServiceConfiguration';
export class InternalServiceActionData {
    'serviceConfiguration'?: InternalServiceActionDataServiceConfiguration | null;
    /**
    * Flow action status.
    */
    'status'?: InternalServiceActionData.StatusEnum | 'disabled' | 'draft' | 'live' | 'manual' = InternalServiceActionData.StatusEnum.Draft;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serviceConfiguration",
            "baseName": "service_configuration",
            "type": "InternalServiceActionDataServiceConfiguration"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "InternalServiceActionData.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return InternalServiceActionData.attributeTypeMap;
    }
}

export namespace InternalServiceActionData {
    export enum StatusEnum {
        Disabled = <any> 'disabled',
        Draft = <any> 'draft',
        Live = <any> 'live',
        Manual = <any> 'manual'
    }
}
