/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class InternalScheduledReportBuilderReportData {
    'serviceMethodType': InternalScheduledReportBuilderReportData.ServiceMethodTypeEnum | 'schedule-report-builder-report';
    'reportId': string;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serviceMethodType",
            "baseName": "service_method_type",
            "type": "InternalScheduledReportBuilderReportData.ServiceMethodTypeEnum"
        },
        {
            "name": "reportId",
            "baseName": "report_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InternalScheduledReportBuilderReportData.attributeTypeMap;
    }
}

export namespace InternalScheduledReportBuilderReportData {
    export enum ServiceMethodTypeEnum {
        ScheduleReportBuilderReport = <any> 'schedule-report-builder-report'
    }
}
