/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScheduleReportEnum } from './scheduleReportEnum';
export class InternalScheduledReportData {
    'serviceMethodType': ScheduleReportEnum | 'schedule-report';
    'reportId': string;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serviceMethodType",
            "baseName": "service_method_type",
            "type": "ScheduleReportEnum"
        },
        {
            "name": "reportId",
            "baseName": "report_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InternalScheduledReportData.attributeTypeMap;
    }
}

export namespace InternalScheduledReportData {
}
