/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class InTheLastBaseRelativeDateFilter {
    'type': InTheLastBaseRelativeDateFilter.TypeEnum | 'date';
    'operator': InTheLastBaseRelativeDateFilter.OperatorEnum | 'in-the-last';
    /**
    * Units for relative date filters.
    */
    'unit': InTheLastBaseRelativeDateFilter.UnitEnum | 'day' | 'hour' | 'week';
    'quantity': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InTheLastBaseRelativeDateFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "InTheLastBaseRelativeDateFilter.OperatorEnum"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "InTheLastBaseRelativeDateFilter.UnitEnum"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InTheLastBaseRelativeDateFilter.attributeTypeMap;
    }
}

export namespace InTheLastBaseRelativeDateFilter {
    export enum TypeEnum {
        Date = <any> 'date'
    }
    export enum OperatorEnum {
        InTheLast = <any> 'in-the-last'
    }
    export enum UnitEnum {
        Day = <any> 'day',
        Hour = <any> 'hour',
        Week = <any> 'week'
    }
}
