/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BounceDateFilterFilter } from './bounceDateFilterFilter';
export class InvalidEmailDateFilter {
    'field': InvalidEmailDateFilter.FieldEnum | 'invalid_email_date';
    'filter': BounceDateFilterFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "InvalidEmailDateFilter.FieldEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "BounceDateFilterFilter"
        }    ];

    static getAttributeTypeMap() {
        return InvalidEmailDateFilter.attributeTypeMap;
    }
}

export namespace InvalidEmailDateFilter {
    export enum FieldEnum {
        InvalidEmailDate = <any> 'invalid_email_date'
    }
}
