/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class IsSetExistenceFilter {
    'type': IsSetExistenceFilter.TypeEnum | 'existence';
    'operator': IsSetExistenceFilter.OperatorEnum | 'is-set';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "IsSetExistenceFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "IsSetExistenceFilter.OperatorEnum"
        }    ];

    static getAttributeTypeMap() {
        return IsSetExistenceFilter.attributeTypeMap;
    }
}

export namespace IsSetExistenceFilter {
    export enum TypeEnum {
        Existence = <any> 'existence'
    }
    export enum OperatorEnum {
        IsSet = <any> 'is-set'
    }
}
