/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class LessThanPositiveNumericFilter {
    'type': LessThanPositiveNumericFilter.TypeEnum | 'numeric';
    'operator': LessThanPositiveNumericFilter.OperatorEnum | 'less-than';
    'value': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "LessThanPositiveNumericFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "LessThanPositiveNumericFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return LessThanPositiveNumericFilter.attributeTypeMap;
    }
}

export namespace LessThanPositiveNumericFilter {
    export enum TypeEnum {
        Numeric = <any> 'numeric'
    }
    export enum OperatorEnum {
        LessThan = <any> 'less-than'
    }
}
