/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LinkStyleStyles } from './linkStyleStyles';
export class LinkStyle {
    'id'?: string | null;
    'styleType': LinkStyle.StyleTypeEnum | 'link-styles';
    'styles': LinkStyleStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "styleType",
            "baseName": "style_type",
            "type": "LinkStyle.StyleTypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "LinkStyleStyles"
        }    ];

    static getAttributeTypeMap() {
        return LinkStyle.attributeTypeMap;
    }
}

export namespace LinkStyle {
    export enum StyleTypeEnum {
        LinkStyles = <any> 'link-styles'
    }
}
