/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class LinkStyleStyles {
    'color'?: string | null;
    /**
    * Font style.
    */
    'fontStyle'?: LinkStyleStyles.FontStyleEnum | 'italic' | 'normal' | null;
    'fontWeight'?: string | null;
    'textDecoration'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "fontStyle",
            "baseName": "font_style",
            "type": "LinkStyleStyles.FontStyleEnum"
        },
        {
            "name": "fontWeight",
            "baseName": "font_weight",
            "type": "string"
        },
        {
            "name": "textDecoration",
            "baseName": "text_decoration",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LinkStyleStyles.attributeTypeMap;
    }
}

export namespace LinkStyleStyles {
    export enum FontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
}
