/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ListSubstringFilter {
    'type': ListSubstringFilter.TypeEnum | 'list';
    /**
    * Operators for list substring filters.
    */
    'operator': ListSubstringFilter.OperatorEnum | 'contains-substring' | 'not-contains-substring';
    'value': string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ListSubstringFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ListSubstringFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListSubstringFilter.attributeTypeMap;
    }
}

export namespace ListSubstringFilter {
    export enum TypeEnum {
        List = <any> 'list'
    }
    export enum OperatorEnum {
        ContainsSubstring = <any> 'contains-substring',
        NotContainsSubstring = <any> 'not-contains-substring'
    }
}
