/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ListRegexOperatorListContainsFilter {
    'type': ListRegexOperatorListContainsFilter.TypeEnum | 'list';
    /**
    * Operators for list regex filters.
    */
    'operator': ListRegexOperatorListContainsFilter.OperatorEnum | 'contains-ends-with' | 'contains-starts-with' | 'not-contains-ends-with' | 'not-contains-starts-with';
    'value': string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ListRegexOperatorListContainsFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ListRegexOperatorListContainsFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListRegexOperatorListContainsFilter.attributeTypeMap;
    }
}

export namespace ListRegexOperatorListContainsFilter {
    export enum TypeEnum {
        List = <any> 'list'
    }
    export enum OperatorEnum {
        ContainsEndsWith = <any> 'contains-ends-with',
        ContainsStartsWith = <any> 'contains-starts-with',
        NotContainsEndsWith = <any> 'not-contains-ends-with',
        NotContainsStartsWith = <any> 'not-contains-starts-with'
    }
}
