/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListContainsOperatorListContainsFilterValue } from './listContainsOperatorListContainsFilterValue';
export class ListContainsOperatorListContainsFilter {
    'type': ListContainsOperatorListContainsFilter.TypeEnum | 'list';
    /**
    * Operators for list contains filters.
    */
    'operator': ListContainsOperatorListContainsFilter.OperatorEnum | 'contains' | 'not-contains';
    'value': ListContainsOperatorListContainsFilterValue | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ListContainsOperatorListContainsFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ListContainsOperatorListContainsFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ListContainsOperatorListContainsFilterValue"
        }    ];

    static getAttributeTypeMap() {
        return ListContainsOperatorListContainsFilter.attributeTypeMap;
    }
}

export namespace ListContainsOperatorListContainsFilter {
    export enum TypeEnum {
        List = <any> 'list'
    }
    export enum OperatorEnum {
        Contains = <any> 'contains',
        NotContains = <any> 'not-contains'
    }
}
