/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ListSetFilter {
    'type': ListSetFilter.TypeEnum | 'list';
    /**
    * Operators for list contains set filters.
    */
    'operator': ListSetFilter.OperatorEnum | 'contains-all' | 'contains-any' | 'not-contains-all' | 'not-contains-any';
    'value': Array<string>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ListSetFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ListSetFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ListSetFilter.attributeTypeMap;
    }
}

export namespace ListSetFilter {
    export enum TypeEnum {
        List = <any> 'list'
    }
    export enum OperatorEnum {
        ContainsAll = <any> 'contains-all',
        ContainsAny = <any> 'contains-any',
        NotContainsAll = <any> 'not-contains-all',
        NotContainsAny = <any> 'not-contains-any'
    }
}
