/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ListLengthFilter {
    'type': ListLengthFilter.TypeEnum | 'list';
    /**
    * Operators for list length filters.
    */
    'operator': ListLengthFilter.OperatorEnum | 'length-equals' | 'length-greater-than' | 'length-greater-than-or-equal' | 'length-less-than' | 'length-less-than-or-equal';
    'value': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ListLengthFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ListLengthFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListLengthFilter.attributeTypeMap;
    }
}

export namespace ListLengthFilter {
    export enum TypeEnum {
        List = <any> 'list'
    }
    export enum OperatorEnum {
        Equals = <any> 'length-equals',
        GreaterThan = <any> 'length-greater-than',
        GreaterThanOrEqual = <any> 'length-greater-than-or-equal',
        LessThan = <any> 'length-less-than',
        LessThanOrEqual = <any> 'length-less-than-or-equal'
    }
}
