/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class MailboxProviderMethodFilter {
    'field': MailboxProviderMethodFilter.FieldEnum | 'method';
    'method': MailboxProviderMethodFilter.MethodEnum | 'mailbox_provider';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "MailboxProviderMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "MailboxProviderMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return MailboxProviderMethodFilter.attributeTypeMap;
    }
}

export namespace MailboxProviderMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        MailboxProvider = <any> 'mailbox_provider'
    }
}
