/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ManualRemoveMethodFilter {
    'field': ManualRemoveMethodFilter.FieldEnum | 'method';
    'method': ManualRemoveMethodFilter.MethodEnum | 'manual_remove';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ManualRemoveMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ManualRemoveMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return ManualRemoveMethodFilter.attributeTypeMap;
    }
}

export namespace ManualRemoveMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        ManualRemove = <any> 'manual_remove'
    }
}
