/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InStringArrayFilter } from './inStringArrayFilter';
export class ManualImportManualMethodFilter {
    'field': ManualImportManualMethodFilter.FieldEnum | 'method';
    'method': ManualImportManualMethodFilter.MethodEnum | 'manual_import';
    'filter'?: InStringArrayFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ManualImportManualMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ManualImportManualMethodFilter.MethodEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "InStringArrayFilter"
        }    ];

    static getAttributeTypeMap() {
        return ManualImportManualMethodFilter.attributeTypeMap;
    }
}

export namespace ManualImportManualMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        ManualImport = <any> 'manual_import'
    }
}
