/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ManualImportMethodFilter {
    'field': ManualImportMethodFilter.FieldEnum | 'method';
    'method': ManualImportMethodFilter.MethodEnum | 'manual_import';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ManualImportMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ManualImportMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return ManualImportMethodFilter.attributeTypeMap;
    }
}

export namespace ManualImportMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        ManualImport = <any> 'manual_import'
    }
}
