/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BounceDateFilterFilter } from './bounceDateFilterFilter';
export class ManualSuppressionDateFilter {
    'field': ManualSuppressionDateFilter.FieldEnum | 'manual_suppression_date';
    'filter': BounceDateFilterFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ManualSuppressionDateFilter.FieldEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "BounceDateFilterFilter"
        }    ];

    static getAttributeTypeMap() {
        return ManualSuppressionDateFilter.attributeTypeMap;
    }
}

export namespace ManualSuppressionDateFilter {
    export enum FieldEnum {
        ManualSuppressionDate = <any> 'manual_suppression_date'
    }
}
