/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MetricPropertyResponseObjectResourceAttributes } from './metricPropertyResponseObjectResourceAttributes';
import { MetricPropertyResponseObjectResourceExtendedAttributesAllOfSampleValuesInner } from './metricPropertyResponseObjectResourceExtendedAttributesAllOfSampleValuesInner';
export class MetricPropertyResponseObjectResourceExtendedAttributes extends MetricPropertyResponseObjectResourceAttributes {
    'sampleValues'?: Array<MetricPropertyResponseObjectResourceExtendedAttributesAllOfSampleValuesInner> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sampleValues",
            "baseName": "sample_values",
            "type": "Array<MetricPropertyResponseObjectResourceExtendedAttributesAllOfSampleValuesInner>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MetricPropertyResponseObjectResourceExtendedAttributes.attributeTypeMap);
    }
}

