/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MetricResponseObjectResourceRelationshipsFlowTriggers } from './metricResponseObjectResourceRelationshipsFlowTriggers';
export class MetricResponseObjectResourceRelationships {
    'flowTriggers'?: MetricResponseObjectResourceRelationshipsFlowTriggers;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flowTriggers",
            "baseName": "flow-triggers",
            "type": "MetricResponseObjectResourceRelationshipsFlowTriggers"
        }    ];

    static getAttributeTypeMap() {
        return MetricResponseObjectResourceRelationships.attributeTypeMap;
    }
}

