/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MobilePushContentCreate } from './mobilePushContentCreate';
import { MobilePushOptions } from './mobilePushOptions';
export class MobilePushMessageStandardDefinitionCreate {
    'channel': MobilePushMessageStandardDefinitionCreate.ChannelEnum | 'mobile_push';
    'content': MobilePushContentCreate;
    /**
    * The key-value pairs to be sent with the push notification
    */
    'kvPairs'?: object | null;
    'options'?: MobilePushOptions;
    /**
    * The type of notification to send
    */
    'notificationType'?: MobilePushMessageStandardDefinitionCreate.NotificationTypeEnum | 'standard' = MobilePushMessageStandardDefinitionCreate.NotificationTypeEnum.Standard;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "MobilePushMessageStandardDefinitionCreate.ChannelEnum"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "MobilePushContentCreate"
        },
        {
            "name": "kvPairs",
            "baseName": "kv_pairs",
            "type": "object"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "MobilePushOptions"
        },
        {
            "name": "notificationType",
            "baseName": "notification_type",
            "type": "MobilePushMessageStandardDefinitionCreate.NotificationTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return MobilePushMessageStandardDefinitionCreate.attributeTypeMap;
    }
}

export namespace MobilePushMessageStandardDefinitionCreate {
    export enum ChannelEnum {
        MobilePush = <any> 'mobile_push'
    }
    export enum NotificationTypeEnum {
        Standard = <any> 'standard'
    }
}
