/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class MobilePushMessageSilentDefinition {
    'channel': MobilePushMessageSilentDefinition.ChannelEnum | 'mobile_push';
    /**
    * The type of notification to send
    */
    'notificationType': MobilePushMessageSilentDefinition.NotificationTypeEnum | 'silent';
    /**
    * The key-value pairs to be sent with the push notification
    */
    'kvPairs'?: object | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "MobilePushMessageSilentDefinition.ChannelEnum"
        },
        {
            "name": "notificationType",
            "baseName": "notification_type",
            "type": "MobilePushMessageSilentDefinition.NotificationTypeEnum"
        },
        {
            "name": "kvPairs",
            "baseName": "kv_pairs",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return MobilePushMessageSilentDefinition.attributeTypeMap;
    }
}

export namespace MobilePushMessageSilentDefinition {
    export enum ChannelEnum {
        MobilePush = <any> 'mobile_push'
    }
    export enum NotificationTypeEnum {
        Silent = <any> 'silent'
    }
}
