/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class MobileStyleProperties {
    'mobilePaddingOverride'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mobilePaddingOverride",
            "baseName": "mobile_padding_override",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return MobileStyleProperties.attributeTypeMap;
    }
}

