/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MobileStyleProperties } from './mobileStyleProperties';
import { MobileStyleStyles } from './mobileStyleStyles';
export class MobileStyle {
    'id'?: string | null;
    'styleType': MobileStyle.StyleTypeEnum | 'mobile-styles';
    'properties': MobileStyleProperties;
    'styles': MobileStyleStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "styleType",
            "baseName": "style_type",
            "type": "MobileStyle.StyleTypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "MobileStyleProperties"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "MobileStyleStyles"
        }    ];

    static getAttributeTypeMap() {
        return MobileStyle.attributeTypeMap;
    }
}

export namespace MobileStyle {
    export enum StyleTypeEnum {
        MobileStyles = <any> 'mobile-styles'
    }
}
