/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MobilePushContentUpdate } from './mobilePushContentUpdate';
import { MobilePushOptions } from './mobilePushOptions';
export class MobilePushMessageStandardDefinitionUpdate {
    'channel': MobilePushMessageStandardDefinitionUpdate.ChannelEnum | 'mobile_push';
    /**
    * The key-value pairs to be sent with the push notification
    */
    'kvPairs'?: object | null;
    'content'?: MobilePushContentUpdate;
    'options'?: MobilePushOptions;
    /**
    * The type of notification to send
    */
    'notificationType'?: MobilePushMessageStandardDefinitionUpdate.NotificationTypeEnum | 'standard' = MobilePushMessageStandardDefinitionUpdate.NotificationTypeEnum.Standard;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "MobilePushMessageStandardDefinitionUpdate.ChannelEnum"
        },
        {
            "name": "kvPairs",
            "baseName": "kv_pairs",
            "type": "object"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "MobilePushContentUpdate"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "MobilePushOptions"
        },
        {
            "name": "notificationType",
            "baseName": "notification_type",
            "type": "MobilePushMessageStandardDefinitionUpdate.NotificationTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return MobilePushMessageStandardDefinitionUpdate.attributeTypeMap;
    }
}

export namespace MobilePushMessageStandardDefinitionUpdate {
    export enum ChannelEnum {
        MobilePush = <any> 'mobile_push'
    }
    export enum NotificationTypeEnum {
        Standard = <any> 'standard'
    }
}
