/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MobilePushContent } from './mobilePushContent';
import { MobilePushOptions } from './mobilePushOptions';
export class MobilePushMessageStandardDefinition {
    'channel': MobilePushMessageStandardDefinition.ChannelEnum | 'mobile_push';
    /**
    * The type of notification to send
    */
    'notificationType': MobilePushMessageStandardDefinition.NotificationTypeEnum | 'standard';
    'content': MobilePushContent;
    /**
    * The key-value pairs to be sent with the push notification
    */
    'kvPairs'?: object | null;
    'options'?: MobilePushOptions;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "MobilePushMessageStandardDefinition.ChannelEnum"
        },
        {
            "name": "notificationType",
            "baseName": "notification_type",
            "type": "MobilePushMessageStandardDefinition.NotificationTypeEnum"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "MobilePushContent"
        },
        {
            "name": "kvPairs",
            "baseName": "kv_pairs",
            "type": "object"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "MobilePushOptions"
        }    ];

    static getAttributeTypeMap() {
        return MobilePushMessageStandardDefinition.attributeTypeMap;
    }
}

export namespace MobilePushMessageStandardDefinition {
    export enum ChannelEnum {
        MobilePush = <any> 'mobile_push'
    }
    export enum NotificationTypeEnum {
        Standard = <any> 'standard'
    }
}
