/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Link } from './link';
import { MultiBranchSplitBranchBranchFilter } from './multiBranchSplitBranchBranchFilter';
export class MultiBranchSplitBranch {
    'branchId': string;
    'order'?: number | null;
    'isElse'?: boolean = false;
    'branchFilter'?: MultiBranchSplitBranchBranchFilter | null;
    'links'?: Link;
    'name'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "branchId",
            "baseName": "branch_id",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        },
        {
            "name": "isElse",
            "baseName": "is_else",
            "type": "boolean"
        },
        {
            "name": "branchFilter",
            "baseName": "branch_filter",
            "type": "MultiBranchSplitBranchBranchFilter"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Link"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MultiBranchSplitBranch.attributeTypeMap;
    }
}

