/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MultiBranchSplitActionData } from './multiBranchSplitActionData';
import { MultiBranchSplitEnum } from './multiBranchSplitEnum';
export class MultiBranchSplitAction {
    /**
    * The real ID of an action. Not allowed on create.
    */
    'id'?: string | null;
    /**
    * A temporary ID to use only during a create operation. Existing actions should use the id field.
    */
    'temporaryId'?: string | null;
    'type': MultiBranchSplitEnum | 'multi-branch-split';
    'links'?: any | null;
    'data'?: MultiBranchSplitActionData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "temporaryId",
            "baseName": "temporary_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MultiBranchSplitEnum"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "any"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "MultiBranchSplitActionData"
        }    ];

    static getAttributeTypeMap() {
        return MultiBranchSplitAction.attributeTypeMap;
    }
}

export namespace MultiBranchSplitAction {
}
