/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MultiBranchSplitBranch } from './multiBranchSplitBranch';
export class MultiBranchSplitActionData {
    'branches': Array<MultiBranchSplitBranch>;
    'name': string;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "branches",
            "baseName": "branches",
            "type": "Array<MultiBranchSplitBranch>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MultiBranchSplitActionData.attributeTypeMap;
    }
}

