/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NextStepProperties } from './nextStepProperties';
export class NextStep {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'submit': boolean;
    'type': NextStep.TypeEnum | 'next_step';
    'properties'?: NextStepProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "submit",
            "baseName": "submit",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NextStep.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "NextStepProperties"
        }    ];

    static getAttributeTypeMap() {
        return NextStep.attributeTypeMap;
    }
}

export namespace NextStep {
    export enum TypeEnum {
        NextStep = <any> 'next_step'
    }
}
