/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NoEmailMarketingFiltersInner } from './noEmailMarketingFiltersInner';
export class NoEmailMarketing {
    'subscription': NoEmailMarketing.SubscriptionEnum | 'any';
    'filters'?: Array<NoEmailMarketingFiltersInner> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "NoEmailMarketing.SubscriptionEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<NoEmailMarketingFiltersInner>"
        }    ];

    static getAttributeTypeMap() {
        return NoEmailMarketing.attributeTypeMap;
    }
}

export namespace NoEmailMarketing {
    export enum SubscriptionEnum {
        Any = <any> 'any'
    }
}
