/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NoSMSMarketingConsentConsentStatus } from './noSMSMarketingConsentConsentStatus';
export class NoSMSMarketingConsent {
    'channel': NoSMSMarketingConsent.ChannelEnum | 'sms';
    'canReceiveMarketing': boolean;
    'consentStatus': NoSMSMarketingConsentConsentStatus;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "NoSMSMarketingConsent.ChannelEnum"
        },
        {
            "name": "canReceiveMarketing",
            "baseName": "can_receive_marketing",
            "type": "boolean"
        },
        {
            "name": "consentStatus",
            "baseName": "consent_status",
            "type": "NoSMSMarketingConsentConsentStatus"
        }    ];

    static getAttributeTypeMap() {
        return NoSMSMarketingConsent.attributeTypeMap;
    }
}

export namespace NoSMSMarketingConsent {
    export enum ChannelEnum {
        Sms = <any> 'sms'
    }
}
