/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class NoSMSMarketing {
    'subscription': NoSMSMarketing.SubscriptionEnum | 'any';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "NoSMSMarketing.SubscriptionEnum"
        }    ];

    static getAttributeTypeMap() {
        return NoSMSMarketing.attributeTypeMap;
    }
}

export namespace NoSMSMarketing {
    export enum SubscriptionEnum {
        Any = <any> 'any'
    }
}
