/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NoSMSMarketingUnsubscribedFiltersInner } from './noSMSMarketingUnsubscribedFiltersInner';
export class NoSMSMarketingUnsubscribed {
    'subscription': NoSMSMarketingUnsubscribed.SubscriptionEnum | 'unsubscribed';
    'filters'?: Array<NoSMSMarketingUnsubscribedFiltersInner> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "NoSMSMarketingUnsubscribed.SubscriptionEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<NoSMSMarketingUnsubscribedFiltersInner>"
        }    ];

    static getAttributeTypeMap() {
        return NoSMSMarketingUnsubscribed.attributeTypeMap;
    }
}

export namespace NoSMSMarketingUnsubscribed {
    export enum SubscriptionEnum {
        Unsubscribed = <any> 'unsubscribed'
    }
}
