/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class OneClickUnsubscribeMethodFilter {
    'field': OneClickUnsubscribeMethodFilter.FieldEnum | 'method';
    'method': OneClickUnsubscribeMethodFilter.MethodEnum | 'one_click_unsubscribe';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "OneClickUnsubscribeMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "OneClickUnsubscribeMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return OneClickUnsubscribeMethodFilter.attributeTypeMap;
    }
}

export namespace OneClickUnsubscribeMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        OneClickUnsubscribe = <any> 'one_click_unsubscribe'
    }
}
