/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MethodEnum } from './methodEnum';
import { OneClickUnsubscribeEnum } from './oneClickUnsubscribeEnum';
export class OneClickUnsubscribeMethodFilter {
    'field': MethodEnum | 'method';
    'method': OneClickUnsubscribeEnum | 'one_click_unsubscribe';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "MethodEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "OneClickUnsubscribeEnum"
        }    ];

    static getAttributeTypeMap() {
        return OneClickUnsubscribeMethodFilter.attributeTypeMap;
    }
}

export namespace OneClickUnsubscribeMethodFilter {
}
