/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowActionEncodedResponseObjectResourceRelationshipsFlowMessages } from './flowActionEncodedResponseObjectResourceRelationshipsFlowMessages';
import { MetricResponseObjectResourceRelationshipsFlowTriggers } from './metricResponseObjectResourceRelationshipsFlowTriggers';
export class PostFlowValuesResponseDTODataRelationships {
    'flows'?: MetricResponseObjectResourceRelationshipsFlowTriggers;
    'flowMessages'?: FlowActionEncodedResponseObjectResourceRelationshipsFlowMessages;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flows",
            "baseName": "flows",
            "type": "MetricResponseObjectResourceRelationshipsFlowTriggers"
        },
        {
            "name": "flowMessages",
            "baseName": "flow-messages",
            "type": "FlowActionEncodedResponseObjectResourceRelationshipsFlowMessages"
        }    ];

    static getAttributeTypeMap() {
        return PostFlowValuesResponseDTODataRelationships.attributeTypeMap;
    }
}

