/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ProductBlockStyles {
    'blockBackgroundColor'?: string | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    /**
    * Text Alignment.
    */
    'buttonAlignment'?: ProductBlockStyles.ButtonAlignmentEnum | 'center' | 'left' | 'right' | null;
    'buttonBackgroundColor'?: string | null;
    'buttonBorderColor'?: string | null;
    'buttonBorderRadius'?: number | null;
    /**
    * Border style.
    */
    'buttonBorderStyle'?: ProductBlockStyles.ButtonBorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'buttonBorderWidth'?: number | null;
    'buttonDropShadowColor'?: string | null;
    'buttonFontColor'?: string | null;
    'buttonFontFamily'?: string | null;
    'buttonFontSize'?: number | null;
    /**
    * Font style.
    */
    'buttonFontStyle'?: ProductBlockStyles.ButtonFontStyleEnum | 'italic' | 'normal' | null;
    'buttonFontWeight'?: string | null;
    'buttonLetterSpacing'?: number | null;
    'buttonPaddingBottom'?: number | null;
    'buttonPaddingLeft'?: number | null;
    'buttonPaddingRight'?: number | null;
    'buttonPaddingTop'?: number | null;
    'buttonTextDecoration'?: string | null;
    'descriptionFontColor'?: string | null;
    'descriptionFontFamily'?: string | null;
    'descriptionFontSize'?: number | null;
    /**
    * Font style.
    */
    'descriptionFontStyle'?: ProductBlockStyles.DescriptionFontStyleEnum | 'italic' | 'normal' | null;
    'descriptionFontWeight'?: string | null;
    'descriptionLetterSpacing'?: number | null;
    'descriptionPaddingBottom'?: number | null;
    'descriptionPaddingTop'?: number | null;
    'descriptionTextDecoration'?: string | null;
    'itemBorderColor'?: string | null;
    /**
    * Border style.
    */
    'itemBorderStyle'?: ProductBlockStyles.ItemBorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'itemBorderWidth'?: number | null;
    'itemMaxHeight'?: number | null;
    'itemPaddingBottom'?: number | null;
    'itemPaddingLeft'?: number | null;
    'itemPaddingRight'?: number | null;
    'itemPaddingTop'?: number | null;
    /**
    * Text Alignment.
    */
    'itemTextAlignment'?: ProductBlockStyles.ItemTextAlignmentEnum | 'center' | 'left' | 'right' | null;
    /**
    * Product layout options.
    */
    'layout'?: ProductBlockStyles.LayoutEnum | 'horizontal' | 'vertical-left-image' | 'vertical-right-image' | null;
    'numColumns'?: number | null;
    'numRows'?: number | null;
    'originalPriceFontColor'?: string | null;
    'originalPriceFontFamily'?: string | null;
    'originalPriceFontSize'?: number | null;
    /**
    * Font style.
    */
    'originalPriceFontStyle'?: ProductBlockStyles.OriginalPriceFontStyleEnum | 'italic' | 'normal' | null;
    'originalPriceFontWeight'?: string | null;
    'originalPriceTextDecoration'?: string | null;
    'priceFontColor'?: string | null;
    'priceFontFamily'?: string | null;
    'priceFontSize'?: number | null;
    /**
    * Font style.
    */
    'priceFontStyle'?: ProductBlockStyles.PriceFontStyleEnum | 'italic' | 'normal' | null;
    'priceFontWeight'?: string | null;
    'priceLetterSpacing'?: number | null;
    'pricePaddingBottom'?: number | null;
    'pricePaddingTop'?: number | null;
    'priceTextDecoration'?: string | null;
    'ratingFontColor'?: string | null;
    'ratingFontFamily'?: string | null;
    'ratingFontSize'?: number | null;
    /**
    * Font style.
    */
    'ratingFontStyle'?: ProductBlockStyles.RatingFontStyleEnum | 'italic' | 'normal' | null;
    'ratingFontWeight'?: string | null;
    'ratingLetterSpacing'?: number | null;
    'ratingPaddingBottom'?: number | null;
    'ratingPaddingTop'?: number | null;
    'ratingTextDecoration'?: string | null;
    'stackOnMobile'?: boolean | null;
    'titleFontColor'?: string | null;
    'titleFontFamily'?: string | null;
    'titleFontSize'?: number | null;
    /**
    * Font style.
    */
    'titleFontStyle'?: ProductBlockStyles.TitleFontStyleEnum | 'italic' | 'normal' | null;
    'titleFontWeight'?: string | null;
    'titleLetterSpacing'?: number | null;
    'titlePaddingBottom'?: number | null;
    'titlePaddingTop'?: number | null;
    'titleTextDecoration'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "buttonAlignment",
            "baseName": "button_alignment",
            "type": "ProductBlockStyles.ButtonAlignmentEnum"
        },
        {
            "name": "buttonBackgroundColor",
            "baseName": "button_background_color",
            "type": "string"
        },
        {
            "name": "buttonBorderColor",
            "baseName": "button_border_color",
            "type": "string"
        },
        {
            "name": "buttonBorderRadius",
            "baseName": "button_border_radius",
            "type": "number"
        },
        {
            "name": "buttonBorderStyle",
            "baseName": "button_border_style",
            "type": "ProductBlockStyles.ButtonBorderStyleEnum"
        },
        {
            "name": "buttonBorderWidth",
            "baseName": "button_border_width",
            "type": "number"
        },
        {
            "name": "buttonDropShadowColor",
            "baseName": "button_drop_shadow_color",
            "type": "string"
        },
        {
            "name": "buttonFontColor",
            "baseName": "button_font_color",
            "type": "string"
        },
        {
            "name": "buttonFontFamily",
            "baseName": "button_font_family",
            "type": "string"
        },
        {
            "name": "buttonFontSize",
            "baseName": "button_font_size",
            "type": "number"
        },
        {
            "name": "buttonFontStyle",
            "baseName": "button_font_style",
            "type": "ProductBlockStyles.ButtonFontStyleEnum"
        },
        {
            "name": "buttonFontWeight",
            "baseName": "button_font_weight",
            "type": "string"
        },
        {
            "name": "buttonLetterSpacing",
            "baseName": "button_letter_spacing",
            "type": "number"
        },
        {
            "name": "buttonPaddingBottom",
            "baseName": "button_padding_bottom",
            "type": "number"
        },
        {
            "name": "buttonPaddingLeft",
            "baseName": "button_padding_left",
            "type": "number"
        },
        {
            "name": "buttonPaddingRight",
            "baseName": "button_padding_right",
            "type": "number"
        },
        {
            "name": "buttonPaddingTop",
            "baseName": "button_padding_top",
            "type": "number"
        },
        {
            "name": "buttonTextDecoration",
            "baseName": "button_text_decoration",
            "type": "string"
        },
        {
            "name": "descriptionFontColor",
            "baseName": "description_font_color",
            "type": "string"
        },
        {
            "name": "descriptionFontFamily",
            "baseName": "description_font_family",
            "type": "string"
        },
        {
            "name": "descriptionFontSize",
            "baseName": "description_font_size",
            "type": "number"
        },
        {
            "name": "descriptionFontStyle",
            "baseName": "description_font_style",
            "type": "ProductBlockStyles.DescriptionFontStyleEnum"
        },
        {
            "name": "descriptionFontWeight",
            "baseName": "description_font_weight",
            "type": "string"
        },
        {
            "name": "descriptionLetterSpacing",
            "baseName": "description_letter_spacing",
            "type": "number"
        },
        {
            "name": "descriptionPaddingBottom",
            "baseName": "description_padding_bottom",
            "type": "number"
        },
        {
            "name": "descriptionPaddingTop",
            "baseName": "description_padding_top",
            "type": "number"
        },
        {
            "name": "descriptionTextDecoration",
            "baseName": "description_text_decoration",
            "type": "string"
        },
        {
            "name": "itemBorderColor",
            "baseName": "item_border_color",
            "type": "string"
        },
        {
            "name": "itemBorderStyle",
            "baseName": "item_border_style",
            "type": "ProductBlockStyles.ItemBorderStyleEnum"
        },
        {
            "name": "itemBorderWidth",
            "baseName": "item_border_width",
            "type": "number"
        },
        {
            "name": "itemMaxHeight",
            "baseName": "item_max_height",
            "type": "number"
        },
        {
            "name": "itemPaddingBottom",
            "baseName": "item_padding_bottom",
            "type": "number"
        },
        {
            "name": "itemPaddingLeft",
            "baseName": "item_padding_left",
            "type": "number"
        },
        {
            "name": "itemPaddingRight",
            "baseName": "item_padding_right",
            "type": "number"
        },
        {
            "name": "itemPaddingTop",
            "baseName": "item_padding_top",
            "type": "number"
        },
        {
            "name": "itemTextAlignment",
            "baseName": "item_text_alignment",
            "type": "ProductBlockStyles.ItemTextAlignmentEnum"
        },
        {
            "name": "layout",
            "baseName": "layout",
            "type": "ProductBlockStyles.LayoutEnum"
        },
        {
            "name": "numColumns",
            "baseName": "num_columns",
            "type": "number"
        },
        {
            "name": "numRows",
            "baseName": "num_rows",
            "type": "number"
        },
        {
            "name": "originalPriceFontColor",
            "baseName": "original_price_font_color",
            "type": "string"
        },
        {
            "name": "originalPriceFontFamily",
            "baseName": "original_price_font_family",
            "type": "string"
        },
        {
            "name": "originalPriceFontSize",
            "baseName": "original_price_font_size",
            "type": "number"
        },
        {
            "name": "originalPriceFontStyle",
            "baseName": "original_price_font_style",
            "type": "ProductBlockStyles.OriginalPriceFontStyleEnum"
        },
        {
            "name": "originalPriceFontWeight",
            "baseName": "original_price_font_weight",
            "type": "string"
        },
        {
            "name": "originalPriceTextDecoration",
            "baseName": "original_price_text_decoration",
            "type": "string"
        },
        {
            "name": "priceFontColor",
            "baseName": "price_font_color",
            "type": "string"
        },
        {
            "name": "priceFontFamily",
            "baseName": "price_font_family",
            "type": "string"
        },
        {
            "name": "priceFontSize",
            "baseName": "price_font_size",
            "type": "number"
        },
        {
            "name": "priceFontStyle",
            "baseName": "price_font_style",
            "type": "ProductBlockStyles.PriceFontStyleEnum"
        },
        {
            "name": "priceFontWeight",
            "baseName": "price_font_weight",
            "type": "string"
        },
        {
            "name": "priceLetterSpacing",
            "baseName": "price_letter_spacing",
            "type": "number"
        },
        {
            "name": "pricePaddingBottom",
            "baseName": "price_padding_bottom",
            "type": "number"
        },
        {
            "name": "pricePaddingTop",
            "baseName": "price_padding_top",
            "type": "number"
        },
        {
            "name": "priceTextDecoration",
            "baseName": "price_text_decoration",
            "type": "string"
        },
        {
            "name": "ratingFontColor",
            "baseName": "rating_font_color",
            "type": "string"
        },
        {
            "name": "ratingFontFamily",
            "baseName": "rating_font_family",
            "type": "string"
        },
        {
            "name": "ratingFontSize",
            "baseName": "rating_font_size",
            "type": "number"
        },
        {
            "name": "ratingFontStyle",
            "baseName": "rating_font_style",
            "type": "ProductBlockStyles.RatingFontStyleEnum"
        },
        {
            "name": "ratingFontWeight",
            "baseName": "rating_font_weight",
            "type": "string"
        },
        {
            "name": "ratingLetterSpacing",
            "baseName": "rating_letter_spacing",
            "type": "number"
        },
        {
            "name": "ratingPaddingBottom",
            "baseName": "rating_padding_bottom",
            "type": "number"
        },
        {
            "name": "ratingPaddingTop",
            "baseName": "rating_padding_top",
            "type": "number"
        },
        {
            "name": "ratingTextDecoration",
            "baseName": "rating_text_decoration",
            "type": "string"
        },
        {
            "name": "stackOnMobile",
            "baseName": "stack_on_mobile",
            "type": "boolean"
        },
        {
            "name": "titleFontColor",
            "baseName": "title_font_color",
            "type": "string"
        },
        {
            "name": "titleFontFamily",
            "baseName": "title_font_family",
            "type": "string"
        },
        {
            "name": "titleFontSize",
            "baseName": "title_font_size",
            "type": "number"
        },
        {
            "name": "titleFontStyle",
            "baseName": "title_font_style",
            "type": "ProductBlockStyles.TitleFontStyleEnum"
        },
        {
            "name": "titleFontWeight",
            "baseName": "title_font_weight",
            "type": "string"
        },
        {
            "name": "titleLetterSpacing",
            "baseName": "title_letter_spacing",
            "type": "number"
        },
        {
            "name": "titlePaddingBottom",
            "baseName": "title_padding_bottom",
            "type": "number"
        },
        {
            "name": "titlePaddingTop",
            "baseName": "title_padding_top",
            "type": "number"
        },
        {
            "name": "titleTextDecoration",
            "baseName": "title_text_decoration",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProductBlockStyles.attributeTypeMap;
    }
}

export namespace ProductBlockStyles {
    export enum ButtonAlignmentEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum ButtonBorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum ButtonFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum DescriptionFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum ItemBorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum ItemTextAlignmentEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum LayoutEnum {
        Horizontal = <any> 'horizontal',
        VerticalLeftImage = <any> 'vertical-left-image',
        VerticalRightImage = <any> 'vertical-right-image'
    }
    export enum OriginalPriceFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum PriceFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum RatingFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum TitleFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
}
