/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProductBlockData } from './productBlockData';
import { ProductSubBlock } from './productSubBlock';
export class ProductBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': ProductBlockV1.ContentTypeEnum | 'block';
    'type': ProductBlockV1.TypeEnum | 'product';
    'data': ProductBlockData;
    'subblocks'?: Array<ProductSubBlock> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "ProductBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ProductBlockData"
        },
        {
            "name": "subblocks",
            "baseName": "subblocks",
            "type": "Array<ProductSubBlock>"
        }    ];

    static getAttributeTypeMap() {
        return ProductBlockV1.attributeTypeMap;
    }
}

export namespace ProductBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Product = <any> 'product'
    }
}
