/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ProductSubBlock {
    'id'?: string | null;
    'type': ProductSubBlock.TypeEnum | 'product';
    'productId'?: string | null;
    'externalId'?: string | null;
    'autogenerateLink'?: boolean | null;
    'buttonText'?: string | null;
    'description'?: string | null;
    'imageUrl'?: string | null;
    'link'?: string | null;
    'name'?: string | null;
    'originalPrice'?: string | null;
    'price'?: string | null;
    'currencyCode'?: string | null;
    'title'?: string | null;
    'url'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductSubBlock.TypeEnum"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "autogenerateLink",
            "baseName": "autogenerate_link",
            "type": "boolean"
        },
        {
            "name": "buttonText",
            "baseName": "button_text",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "originalPrice",
            "baseName": "original_price",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "currencyCode",
            "baseName": "currency_code",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProductSubBlock.attributeTypeMap;
    }
}

export namespace ProductSubBlock {
    export enum TypeEnum {
        Product = <any> 'product'
    }
}
