/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileOperationUpdateOrCreateDatePropertyValue } from './profileOperationUpdateOrCreateDatePropertyValue';
export class ProfileOperationUpdateOrCreateDate {
    /**
    * The type of operation to perform on a profile property.
    */
    'operator': ProfileOperationUpdateOrCreateDate.OperatorEnum | 'create' | 'update';
    'propertyType': ProfileOperationUpdateOrCreateDate.PropertyTypeEnum | 'date';
    'propertyKey': string;
    'propertyValue': ProfileOperationUpdateOrCreateDatePropertyValue;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ProfileOperationUpdateOrCreateDate.OperatorEnum"
        },
        {
            "name": "propertyType",
            "baseName": "property_type",
            "type": "ProfileOperationUpdateOrCreateDate.PropertyTypeEnum"
        },
        {
            "name": "propertyKey",
            "baseName": "property_key",
            "type": "string"
        },
        {
            "name": "propertyValue",
            "baseName": "property_value",
            "type": "ProfileOperationUpdateOrCreateDatePropertyValue"
        }    ];

    static getAttributeTypeMap() {
        return ProfileOperationUpdateOrCreateDate.attributeTypeMap;
    }
}

export namespace ProfileOperationUpdateOrCreateDate {
    export enum OperatorEnum {
        Create = <any> 'create',
        Update = <any> 'update'
    }
    export enum PropertyTypeEnum {
        Date = <any> 'date'
    }
}
