/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BooleanFilter } from './booleanFilter';
import { ExistenceOperatorExistenceFilter } from './existenceOperatorExistenceFilter';
import { ListLengthFilter } from './listLengthFilter';
import { ListSetFilter } from './listSetFilter';
import { ListSubstringFilter } from './listSubstringFilter';
import { NumericOperatorNumericFilter } from './numericOperatorNumericFilter';
import { NumericOperatorNumericFilterValue } from './numericOperatorNumericFilterValue';
import { StringArrayOperatorStringArrayFilter } from './stringArrayOperatorStringArrayFilter';
import { StringOperatorStringFilter } from './stringOperatorStringFilter';
export type ProfileMetricPropertyFilterFilter = StringOperatorStringFilter | StringArrayOperatorStringArrayFilter | ExistenceOperatorExistenceFilter | ListSetFilter | ListLengthFilter | ListSubstringFilter | BooleanFilter | NumericOperatorNumericFilter;
