/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileImportJobResponseObjectResourceRelationshipsImportErrors } from './profileImportJobResponseObjectResourceRelationshipsImportErrors';
import { ProfileImportJobResponseObjectResourceRelationshipsLists } from './profileImportJobResponseObjectResourceRelationshipsLists';
import { ProfileImportJobResponseObjectResourceRelationshipsProfiles } from './profileImportJobResponseObjectResourceRelationshipsProfiles';
export class ProfileImportJobResponseObjectResourceRelationships {
    'lists'?: ProfileImportJobResponseObjectResourceRelationshipsLists;
    'profiles'?: ProfileImportJobResponseObjectResourceRelationshipsProfiles;
    'importErrors'?: ProfileImportJobResponseObjectResourceRelationshipsImportErrors;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lists",
            "baseName": "lists",
            "type": "ProfileImportJobResponseObjectResourceRelationshipsLists"
        },
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "ProfileImportJobResponseObjectResourceRelationshipsProfiles"
        },
        {
            "name": "importErrors",
            "baseName": "import-errors",
            "type": "ProfileImportJobResponseObjectResourceRelationshipsImportErrors"
        }    ];

    static getAttributeTypeMap() {
        return ProfileImportJobResponseObjectResourceRelationships.attributeTypeMap;
    }
}

