/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StatusDateFilterFilter } from './statusDateFilterFilter';
export class ProfilePredictiveAnalyticsDateCondition {
    /**
    * Dimension for date profile predictive analytics conditions.
    */
    'dimension': ProfilePredictiveAnalyticsDateCondition.DimensionEnum | 'expected_date_of_next_purchase';
    'filter': StatusDateFilterFilter;
    'type': ProfilePredictiveAnalyticsDateCondition.TypeEnum | 'profile-predictive-analytics';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "ProfilePredictiveAnalyticsDateCondition.DimensionEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "StatusDateFilterFilter"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfilePredictiveAnalyticsDateCondition.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ProfilePredictiveAnalyticsDateCondition.attributeTypeMap;
    }
}

export namespace ProfilePredictiveAnalyticsDateCondition {
    export enum DimensionEnum {
        ExpectedDateOfNextPurchase = <any> 'expected_date_of_next_purchase'
    }
    export enum TypeEnum {
        ProfilePredictiveAnalytics = <any> 'profile-predictive-analytics'
    }
}
