/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IntegerFilter } from './integerFilter';
import { ProfileHasCustomObjectFilter } from './profileHasCustomObjectFilter';
export class ProfileHasCustomObjectCondition {
    'type': ProfileHasCustomObjectCondition.TypeEnum | 'profile-has-custom-object';
    'objectTypeId': string;
    'objectTypeRelationshipId': string;
    'filter': IntegerFilter;
    'filters': Array<ProfileHasCustomObjectFilter>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileHasCustomObjectCondition.TypeEnum"
        },
        {
            "name": "objectTypeId",
            "baseName": "object_type_id",
            "type": "string"
        },
        {
            "name": "objectTypeRelationshipId",
            "baseName": "object_type_relationship_id",
            "type": "string"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "IntegerFilter"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<ProfileHasCustomObjectFilter>"
        }    ];

    static getAttributeTypeMap() {
        return ProfileHasCustomObjectCondition.attributeTypeMap;
    }
}

export namespace ProfileHasCustomObjectCondition {
    export enum TypeEnum {
        ProfileHasCustomObject = <any> 'profile-has-custom-object'
    }
}
