/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ProfilePredictiveAnalyticsStringFilter {
    'type': ProfilePredictiveAnalyticsStringFilter.TypeEnum | 'string';
    'operator': ProfilePredictiveAnalyticsStringFilter.OperatorEnum | 'equals';
    /**
    * Values for profile predictive analytics gender conditions.
    */
    'value': ProfilePredictiveAnalyticsStringFilter.ValueEnum | 'likely_female' | 'likely_male' | 'uncertain';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfilePredictiveAnalyticsStringFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ProfilePredictiveAnalyticsStringFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ProfilePredictiveAnalyticsStringFilter.ValueEnum"
        }    ];

    static getAttributeTypeMap() {
        return ProfilePredictiveAnalyticsStringFilter.attributeTypeMap;
    }
}

export namespace ProfilePredictiveAnalyticsStringFilter {
    export enum TypeEnum {
        String = <any> 'string'
    }
    export enum OperatorEnum {
        Equals = <any> 'equals'
    }
    export enum ValueEnum {
        LikelyFemale = <any> 'likely_female',
        LikelyMale = <any> 'likely_male',
        Uncertain = <any> 'uncertain'
    }
}
