/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileHasCustomObjectFilterFilter } from './profileHasCustomObjectFilterFilter';
export class ProfileHasCustomObjectFilter {
    'propertyId': number;
    'filter': ProfileHasCustomObjectFilterFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "propertyId",
            "baseName": "property_id",
            "type": "number"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ProfileHasCustomObjectFilterFilter"
        }    ];

    static getAttributeTypeMap() {
        return ProfileHasCustomObjectFilter.attributeTypeMap;
    }
}

