/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileHasNotReceivedPushMessageConditionTimeframeFilter } from './profileHasNotReceivedPushMessageConditionTimeframeFilter';
export class ProfileHasNotReceivedEmailMessageCondition {
    'type': ProfileHasNotReceivedEmailMessageCondition.TypeEnum | 'profile-not-sent-email';
    'timeframeFilter': ProfileHasNotReceivedPushMessageConditionTimeframeFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileHasNotReceivedEmailMessageCondition.TypeEnum"
        },
        {
            "name": "timeframeFilter",
            "baseName": "timeframe_filter",
            "type": "ProfileHasNotReceivedPushMessageConditionTimeframeFilter"
        }    ];

    static getAttributeTypeMap() {
        return ProfileHasNotReceivedEmailMessageCondition.attributeTypeMap;
    }
}

export namespace ProfileHasNotReceivedEmailMessageCondition {
    export enum TypeEnum {
        ProfileNotSentEmail = <any> 'profile-not-sent-email'
    }
}
