/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileHasGroupMembershipConditionTimeframeFilter } from './profileHasGroupMembershipConditionTimeframeFilter';
export class ProfileHasGroupMembershipCondition {
    'type': ProfileHasGroupMembershipCondition.TypeEnum | 'profile-group-membership';
    'isMember': boolean;
    'groupIds': Array<string>;
    'timeframeFilter'?: ProfileHasGroupMembershipConditionTimeframeFilter | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileHasGroupMembershipCondition.TypeEnum"
        },
        {
            "name": "isMember",
            "baseName": "is_member",
            "type": "boolean"
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "Array<string>"
        },
        {
            "name": "timeframeFilter",
            "baseName": "timeframe_filter",
            "type": "ProfileHasGroupMembershipConditionTimeframeFilter"
        }    ];

    static getAttributeTypeMap() {
        return ProfileHasGroupMembershipCondition.attributeTypeMap;
    }
}

export namespace ProfileHasGroupMembershipCondition {
    export enum TypeEnum {
        ProfileGroupMembership = <any> 'profile-group-membership'
    }
}
