/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class PromotionalSMSSubscription {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'submit'?: boolean = true;
    'type': PromotionalSMSSubscription.TypeEnum | 'promotional_sms_subscription';
    'properties'?: PromotionalSMSSubscription.PropertiesEnum | 'null';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "submit",
            "baseName": "submit",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PromotionalSMSSubscription.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "PromotionalSMSSubscription.PropertiesEnum"
        }    ];

    static getAttributeTypeMap() {
        return PromotionalSMSSubscription.attributeTypeMap;
    }
}

export namespace PromotionalSMSSubscription {
    export enum TypeEnum {
        PromotionalSmsSubscription = <any> 'promotional_sms_subscription'
    }
    export enum PropertiesEnum {
        Null = <any> 'null'
    }
}
