/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ProvidedNoAgeMethodFilter {
    'field': ProvidedNoAgeMethodFilter.FieldEnum | 'method';
    'method': ProvidedNoAgeMethodFilter.MethodEnum | 'provided_no_age';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ProvidedNoAgeMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ProvidedNoAgeMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return ProvidedNoAgeMethodFilter.attributeTypeMap;
    }
}

export namespace ProvidedNoAgeMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        ProvidedNoAge = <any> 'provided_no_age'
    }
}
