/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ProvidedLandlineMethodFilter {
    'field': ProvidedLandlineMethodFilter.FieldEnum | 'method';
    'method': ProvidedLandlineMethodFilter.MethodEnum | 'provided_landline';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ProvidedLandlineMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ProvidedLandlineMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return ProvidedLandlineMethodFilter.attributeTypeMap;
    }
}

export namespace ProvidedLandlineMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        ProvidedLandline = <any> 'provided_landline'
    }
}
