/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PushTokenEntry } from './pushTokenEntry';
import { UnsubscriptionParameters } from './unsubscriptionParameters';
export class PushUnsubscriptionParameters {
    'marketing': UnsubscriptionParameters;
    /**
    * A list of push tokens to unsubscribe/remove.
    */
    'tokens': Array<PushTokenEntry>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "marketing",
            "baseName": "marketing",
            "type": "UnsubscriptionParameters"
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<PushTokenEntry>"
        }    ];

    static getAttributeTypeMap() {
        return PushUnsubscriptionParameters.attributeTypeMap;
    }
}

