/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class PushOnOpenApp {
    'type': PushOnOpenApp.TypeEnum | 'open_app';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PushOnOpenApp.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PushOnOpenApp.attributeTypeMap;
    }
}

export namespace PushOnOpenApp {
    export enum TypeEnum {
        OpenApp = <any> 'open_app'
    }
}
