/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PushTokenDeviceMetadata } from './pushTokenDeviceMetadata';
export class PushTokenEntry {
    /**
    * A push token from APNS or FCM.
    */
    'token': string;
    /**
    * The platform on which the push token was created. Either \"ios\" or \"android\".
    */
    'platform': PushTokenEntry.PlatformEnum | 'android' | 'ios';
    /**
    * The vendor of the push token. Either \"apns\" or \"fcm\".
    */
    'vendor': PushTokenEntry.VendorEnum | 'apns' | 'fcm';
    /**
    * The enablement status for the push token.
    */
    'enablementStatus'?: PushTokenEntry.EnablementStatusEnum | 'AUTHORIZED' | 'DENIED' | 'NOT_DETERMINED' | 'PROVISIONAL' | 'UNAUTHORIZED' | null;
    /**
    * The background state of the push token.
    */
    'background'?: PushTokenEntry.BackgroundEnum | 'AVAILABLE' | 'DENIED' | 'RESTRICTED' | null;
    'deviceMetadata'?: PushTokenDeviceMetadata;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PushTokenEntry.PlatformEnum"
        },
        {
            "name": "vendor",
            "baseName": "vendor",
            "type": "PushTokenEntry.VendorEnum"
        },
        {
            "name": "enablementStatus",
            "baseName": "enablement_status",
            "type": "PushTokenEntry.EnablementStatusEnum"
        },
        {
            "name": "background",
            "baseName": "background",
            "type": "PushTokenEntry.BackgroundEnum"
        },
        {
            "name": "deviceMetadata",
            "baseName": "device_metadata",
            "type": "PushTokenDeviceMetadata"
        }    ];

    static getAttributeTypeMap() {
        return PushTokenEntry.attributeTypeMap;
    }
}

export namespace PushTokenEntry {
    export enum PlatformEnum {
        Android = <any> 'android',
        Ios = <any> 'ios'
    }
    export enum VendorEnum {
        Apns = <any> 'apns',
        Fcm = <any> 'fcm'
    }
    export enum EnablementStatusEnum {
        Authorized = <any> 'AUTHORIZED',
        Denied = <any> 'DENIED',
        NotDetermined = <any> 'NOT_DETERMINED',
        Provisional = <any> 'PROVISIONAL',
        Unauthorized = <any> 'UNAUTHORIZED'
    }
    export enum BackgroundEnum {
        Available = <any> 'AVAILABLE',
        Denied = <any> 'DENIED',
        Restricted = <any> 'RESTRICTED'
    }
}
