/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PushTokenEntry } from './pushTokenEntry';
import { SubscriptionParameters } from './subscriptionParameters';
export class PushSubscriptionParameters {
    'marketing': SubscriptionParameters;
    /**
    * A list of push tokens to register for this profile.
    */
    'tokens'?: Array<PushTokenEntry> | null;
    /**
    * An anonymous identifier for push-only profiles with no email/phone.
    */
    'anonymousId'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "marketing",
            "baseName": "marketing",
            "type": "SubscriptionParameters"
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<PushTokenEntry>"
        },
        {
            "name": "anonymousId",
            "baseName": "anonymous_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PushSubscriptionParameters.attributeTypeMap;
    }
}

