/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RedirectProperties } from './redirectProperties';
export class Redirect {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'submit': boolean;
    'type': Redirect.TypeEnum | 'redirect';
    'properties': RedirectProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "submit",
            "baseName": "submit",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Redirect.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "RedirectProperties"
        }    ];

    static getAttributeTypeMap() {
        return Redirect.attributeTypeMap;
    }
}

export namespace Redirect {
    export enum TypeEnum {
        Redirect = <any> 'redirect'
    }
}
