/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReentryCriteriaUnit } from './reentryCriteriaUnit';
export class ReentryCriteria {
    'duration': number;
    'unit': ReentryCriteriaUnit;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "ReentryCriteriaUnit"
        }    ];

    static getAttributeTypeMap() {
        return ReentryCriteria.attributeTypeMap;
    }
}

