/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class RejectReasonUnrelated {
    /**
    * rejected due to unrelated content
    */
    'reason': RejectReasonUnrelated.ReasonEnum | 'unrelated';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "RejectReasonUnrelated.ReasonEnum"
        }    ];

    static getAttributeTypeMap() {
        return RejectReasonUnrelated.attributeTypeMap;
    }
}

export namespace RejectReasonUnrelated {
    export enum ReasonEnum {
        Unrelated = <any> 'unrelated'
    }
}
