/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class RejectReasonFake {
    /**
    * rejected due to fake content
    */
    'reason': RejectReasonFake.ReasonEnum | 'fake';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "RejectReasonFake.ReasonEnum"
        }    ];

    static getAttributeTypeMap() {
        return RejectReasonFake.attributeTypeMap;
    }
}

export namespace RejectReasonFake {
    export enum ReasonEnum {
        Fake = <any> 'fake'
    }
}
