/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class RejectReasonOther {
    /**
    * reject reason is other
    */
    'reason': RejectReasonOther.ReasonEnum | 'other';
    /**
    * If review reject reason is other, we can provide further explanation
    */
    'statusExplanation'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "RejectReasonOther.ReasonEnum"
        },
        {
            "name": "statusExplanation",
            "baseName": "status_explanation",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RejectReasonOther.attributeTypeMap;
    }
}

export namespace RejectReasonOther {
    export enum ReasonEnum {
        Other = <any> 'other'
    }
}
