/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class RejectReasonProfanity {
    /**
    * rejected due to profanity or inappropriate content
    */
    'reason': RejectReasonProfanity.ReasonEnum | 'profanity_or_inappropriate';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "RejectReasonProfanity.ReasonEnum"
        }    ];

    static getAttributeTypeMap() {
        return RejectReasonProfanity.attributeTypeMap;
    }
}

export namespace RejectReasonProfanity {
    export enum ReasonEnum {
        ProfanityOrInappropriate = <any> 'profanity_or_inappropriate'
    }
}
