/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class RejectReasonMisleading {
    /**
    * rejected due to false or misleading content
    */
    'reason': RejectReasonMisleading.ReasonEnum | 'false_or_misleading';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "RejectReasonMisleading.ReasonEnum"
        }    ];

    static getAttributeTypeMap() {
        return RejectReasonMisleading.attributeTypeMap;
    }
}

export namespace RejectReasonMisleading {
    export enum ReasonEnum {
        FalseOrMisleading = <any> 'false_or_misleading'
    }
}
