/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateEnum } from './dateEnum';
export class RelativeDateOperatorBaseRelativeDateFilter {
    'type': DateEnum | 'date';
    /**
    * Operators for relative date filters.  e.g. \"in the last 10 days\"
    */
    'operator': RelativeDateOperatorBaseRelativeDateFilter.OperatorEnum | 'at-least' | 'in-the-last' | 'in-the-next';
    /**
    * Units for relative date filters.
    */
    'unit': RelativeDateOperatorBaseRelativeDateFilter.UnitEnum | 'day' | 'hour' | 'week';
    'quantity': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DateEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "RelativeDateOperatorBaseRelativeDateFilter.OperatorEnum"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "RelativeDateOperatorBaseRelativeDateFilter.UnitEnum"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return RelativeDateOperatorBaseRelativeDateFilter.attributeTypeMap;
    }
}

export namespace RelativeDateOperatorBaseRelativeDateFilter {
    export enum OperatorEnum {
        AtLeast = <any> 'at-least',
        InTheLast = <any> 'in-the-last',
        InTheNext = <any> 'in-the-next'
    }
    export enum UnitEnum {
        Day = <any> 'day',
        Hour = <any> 'hour',
        Week = <any> 'week'
    }
}
