/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ReviewStatusFeatured {
    /**
    * Featured review status
    */
    'value': ReviewStatusFeatured.ValueEnum | 'featured';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "ReviewStatusFeatured.ValueEnum"
        }    ];

    static getAttributeTypeMap() {
        return ReviewStatusFeatured.attributeTypeMap;
    }
}

export namespace ReviewStatusFeatured {
    export enum ValueEnum {
        Featured = <any> 'featured'
    }
}
