/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ReviewStatusUnpublished {
    /**
    * Unpublished review status
    */
    'value': ReviewStatusUnpublished.ValueEnum | 'unpublished';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "ReviewStatusUnpublished.ValueEnum"
        }    ];

    static getAttributeTypeMap() {
        return ReviewStatusUnpublished.attributeTypeMap;
    }
}

export namespace ReviewStatusUnpublished {
    export enum ValueEnum {
        Unpublished = <any> 'unpublished'
    }
}
