/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { ReviewBlockDataProperties } from './reviewBlockDataProperties';
import { ReviewBlockStyles } from './reviewBlockStyles';
export class ReviewBlockData {
    'properties': ReviewBlockDataProperties;
    'displayOptions': DisplayOptions;
    'styles': ReviewBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "ReviewBlockDataProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "ReviewBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return ReviewBlockData.attributeTypeMap;
    }
}

