/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ReviewStatusPublished {
    /**
    * Published review status
    */
    'value': ReviewStatusPublished.ValueEnum | 'published';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "ReviewStatusPublished.ValueEnum"
        }    ];

    static getAttributeTypeMap() {
        return ReviewStatusPublished.attributeTypeMap;
    }
}

export namespace ReviewStatusPublished {
    export enum ValueEnum {
        Published = <any> 'published'
    }
}
