/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class RowStyles {
    /**
    * Column layout.
    */
    'columnLayout'?: RowStyles.ColumnLayoutEnum | '1-column-full-width' | '2-columns-25%-75%' | '2-columns-33%-67%' | '2-columns-67%-33%' | '2-columns-75%-25%' | '2-columns-equal-width' | '3-columns-25%-25%-50%' | '3-columns-25%-50%-25%' | '3-columns-50%-25%-25%' | '3-columns-equal-width' | '4-columns-equal-width' | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "columnLayout",
            "baseName": "column_layout",
            "type": "RowStyles.ColumnLayoutEnum"
        }    ];

    static getAttributeTypeMap() {
        return RowStyles.attributeTypeMap;
    }
}

export namespace RowStyles {
    export enum ColumnLayoutEnum {
        _1ColumnFullWidth = <any> '1-column-full-width',
        _2Columns2575 = <any> '2-columns-25%-75%',
        _2Columns3367 = <any> '2-columns-33%-67%',
        _2Columns6733 = <any> '2-columns-67%-33%',
        _2Columns7525 = <any> '2-columns-75%-25%',
        _2ColumnsEqualWidth = <any> '2-columns-equal-width',
        _3Columns252550 = <any> '3-columns-25%-25%-50%',
        _3Columns255025 = <any> '3-columns-25%-50%-25%',
        _3Columns502525 = <any> '3-columns-50%-25%-25%',
        _3ColumnsEqualWidth = <any> '3-columns-equal-width',
        _4ColumnsEqualWidth = <any> '4-columns-equal-width'
    }
}
