/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RowV0BlocksInner } from './rowV0BlocksInner';
export class RowV0 {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'blocks': Array<RowV0BlocksInner>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "Array<RowV0BlocksInner>"
        }    ];

    static getAttributeTypeMap() {
        return RowV0.attributeTypeMap;
    }
}

