/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponBlockV0Data } from './couponBlockV0Data';
export class SectionV0 {
    'contentType': SectionV0.ContentTypeEnum | 'section';
    'type': SectionV0.TypeEnum | 'section';
    'data': CouponBlockV0Data | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "SectionV0.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SectionV0.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CouponBlockV0Data"
        }    ];

    static getAttributeTypeMap() {
        return SectionV0.attributeTypeMap;
    }
}

export namespace SectionV0 {
    export enum ContentTypeEnum {
        Section = <any> 'section'
    }
    export enum TypeEnum {
        Section = <any> 'section'
    }
}
