/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { SectionProperties } from './sectionProperties';
import { SectionStyles } from './sectionStyles';
export class SectionData {
    'properties': SectionProperties;
    'displayOptions': DisplayOptions;
    'styles': SectionStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "SectionProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "SectionStyles"
        }    ];

    static getAttributeTypeMap() {
        return SectionData.attributeTypeMap;
    }
}

