/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SectionProperties {
    'isAiGenerated'?: boolean | null;
    'isPrebuiltContent'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isAiGenerated",
            "baseName": "is_ai_generated",
            "type": "boolean"
        },
        {
            "name": "isPrebuiltContent",
            "baseName": "is_prebuilt_content",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SectionProperties.attributeTypeMap;
    }
}

