/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SegmentDefinition } from './segmentDefinition';
export class SegmentPartialUpdateQueryResourceObjectAttributes {
    'definition'?: SegmentDefinition;
    'name'?: string | null;
    'isStarred'?: boolean | null;
    /**
    * Set to false to deactivate the segment. When deactivating, this must be the only attribute in the request body. Deactivation cannot be combined with other updates. Marking a segment inactive will impact campaigns, flows, ad syncs, forms, helpdesk routing, and other features that reference this segment. Set to true to reactivate a deactivated segment.
    */
    'isActive'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "definition",
            "baseName": "definition",
            "type": "SegmentDefinition"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "isStarred",
            "baseName": "is_starred",
            "type": "boolean"
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SegmentPartialUpdateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

