/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Link } from './link';
import { SendInternalAlertActionData } from './sendInternalAlertActionData';
export class SendInternalAlertAction {
    /**
    * The real ID of an action. Not allowed on create.
    */
    'id'?: string | null;
    /**
    * A temporary ID to use only during a create operation. Existing actions should use the id field.
    */
    'temporaryId'?: string | null;
    'type': SendInternalAlertAction.TypeEnum | 'send-internal-alert';
    'links'?: Link;
    'data'?: SendInternalAlertActionData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "temporaryId",
            "baseName": "temporary_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SendInternalAlertAction.TypeEnum"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Link"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "SendInternalAlertActionData"
        }    ];

    static getAttributeTypeMap() {
        return SendInternalAlertAction.attributeTypeMap;
    }
}

export namespace SendInternalAlertAction {
    export enum TypeEnum {
        SendInternalAlert = <any> 'send-internal-alert'
    }
}
