/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SendPushNotificationAction } from './sendPushNotificationAction';
import { SendPushNotificationActionCurrentExperiment } from './sendPushNotificationActionCurrentExperiment';
export class SendPushNotificationActionContentExperimentActionData {
    /**
    * Flow action status.
    */
    'status'?: SendPushNotificationActionContentExperimentActionData.StatusEnum | 'disabled' | 'draft' | 'live' | 'manual' = SendPushNotificationActionContentExperimentActionData.StatusEnum.Draft;
    /**
    * Not allowed on create.
    */
    'experimentStatus'?: SendPushNotificationActionContentExperimentActionData.ExperimentStatusEnum | 'completed' | 'draft' | 'live' | null;
    'mainAction': SendPushNotificationAction;
    'currentExperiment'?: SendPushNotificationActionCurrentExperiment;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SendPushNotificationActionContentExperimentActionData.StatusEnum"
        },
        {
            "name": "experimentStatus",
            "baseName": "experiment_status",
            "type": "SendPushNotificationActionContentExperimentActionData.ExperimentStatusEnum"
        },
        {
            "name": "mainAction",
            "baseName": "main_action",
            "type": "SendPushNotificationAction"
        },
        {
            "name": "currentExperiment",
            "baseName": "current_experiment",
            "type": "SendPushNotificationActionCurrentExperiment"
        }    ];

    static getAttributeTypeMap() {
        return SendPushNotificationActionContentExperimentActionData.attributeTypeMap;
    }
}

export namespace SendPushNotificationActionContentExperimentActionData {
    export enum StatusEnum {
        Disabled = <any> 'disabled',
        Draft = <any> 'draft',
        Live = <any> 'live',
        Manual = <any> 'manual'
    }
    export enum ExperimentStatusEnum {
        Completed = <any> 'completed',
        Draft = <any> 'draft',
        Live = <any> 'live'
    }
}
