/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ShopifyIntegrationFilter } from './shopifyIntegrationFilter';
export class ShopifyIntegrationMethodFilter {
    'field': ShopifyIntegrationMethodFilter.FieldEnum | 'method';
    'method': ShopifyIntegrationMethodFilter.MethodEnum | 'integration';
    'filter': ShopifyIntegrationFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "ShopifyIntegrationMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "ShopifyIntegrationMethodFilter.MethodEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ShopifyIntegrationFilter"
        }    ];

    static getAttributeTypeMap() {
        return ShopifyIntegrationMethodFilter.attributeTypeMap;
    }
}

export namespace ShopifyIntegrationMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        Integration = <any> 'integration'
    }
}
