/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SmartSendTimeStrategy {
    'method': SmartSendTimeStrategy.MethodEnum | 'smart_send_time';
    /**
    * The day to send on
    */
    'date': string;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "SmartSendTimeStrategy.MethodEnum"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SmartSendTimeStrategy.attributeTypeMap;
    }
}

export namespace SmartSendTimeStrategy {
    export enum MethodEnum {
        SmartSendTime = <any> 'smart_send_time'
    }
}
