/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TextStyleV0FontFamily } from './textStyleV0FontFamily';
export class SMSDisclosureTextStyle {
    'fontFamily'?: TextStyleV0FontFamily;
    'fontSize'?: number = 16;
    /**
    * Font weight enumeration.
    */
    'fontWeight'?: SMSDisclosureTextStyle.FontWeightEnum | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | null = SMSDisclosureTextStyle.FontWeightEnum.NUMBER_400;
    'textColor'?: string = '#000000';
    'characterSpacing'?: number | null = 0;
    'fontStyle'?: string | null;
    'textDecoration'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fontFamily",
            "baseName": "font_family",
            "type": "TextStyleV0FontFamily"
        },
        {
            "name": "fontSize",
            "baseName": "font_size",
            "type": "number"
        },
        {
            "name": "fontWeight",
            "baseName": "font_weight",
            "type": "SMSDisclosureTextStyle.FontWeightEnum"
        },
        {
            "name": "textColor",
            "baseName": "text_color",
            "type": "string"
        },
        {
            "name": "characterSpacing",
            "baseName": "character_spacing",
            "type": "number"
        },
        {
            "name": "fontStyle",
            "baseName": "font_style",
            "type": "string"
        },
        {
            "name": "textDecoration",
            "baseName": "text_decoration",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SMSDisclosureTextStyle.attributeTypeMap;
    }
}

export namespace SMSDisclosureTextStyle {
    export enum FontWeightEnum {
        NUMBER_100 = <any> 100,
        NUMBER_200 = <any> 200,
        NUMBER_300 = <any> 300,
        NUMBER_400 = <any> 400,
        NUMBER_500 = <any> 500,
        NUMBER_600 = <any> 600,
        NUMBER_700 = <any> 700,
        NUMBER_800 = <any> 800,
        NUMBER_900 = <any> 900
    }
}
