/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RenderOptions } from './renderOptions';
import { SMSContentCreate } from './sMSContentCreate';
export class SMSMessageDefinitionCreate {
    'channel': SMSMessageDefinitionCreate.ChannelEnum | 'sms';
    'content'?: SMSContentCreate;
    'renderOptions'?: RenderOptions;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "SMSMessageDefinitionCreate.ChannelEnum"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "SMSContentCreate"
        },
        {
            "name": "renderOptions",
            "baseName": "render_options",
            "type": "RenderOptions"
        }    ];

    static getAttributeTypeMap() {
        return SMSMessageDefinitionCreate.attributeTypeMap;
    }
}

export namespace SMSMessageDefinitionCreate {
    export enum ChannelEnum {
        Sms = <any> 'sms'
    }
}
