/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SocialBlockData } from './socialBlockData';
import { SocialBlockV1SubblocksInner } from './socialBlockV1SubblocksInner';
export class SocialBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': SocialBlockV1.ContentTypeEnum | 'block';
    'type': SocialBlockV1.TypeEnum | 'social';
    'data': SocialBlockData;
    'subblocks'?: Array<SocialBlockV1SubblocksInner> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "SocialBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SocialBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "SocialBlockData"
        },
        {
            "name": "subblocks",
            "baseName": "subblocks",
            "type": "Array<SocialBlockV1SubblocksInner>"
        }    ];

    static getAttributeTypeMap() {
        return SocialBlockV1.attributeTypeMap;
    }
}

export namespace SocialBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Social = <any> 'social'
    }
}
