/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SocialIconSubBlock {
    'id'?: string | null;
    'type': SocialIconSubBlock.TypeEnum | 'social_link_icon';
    'customAssetId'?: string | null;
    'customSrc'?: string | null;
    'customSize'?: number | null;
    'label'?: string | null;
    /**
    * Social block link type.
    */
    'linkType'?: SocialIconSubBlock.LinkTypeEnum | 'android' | 'apple' | 'custom' | 'discord' | 'email' | 'facebook' | 'google-plus' | 'instagram' | 'linkedin' | 'pinterest' | 'rss' | 'snapchat' | 'threads' | 'tiktok' | 'twitch' | 'twitter' | 'whatsapp' | 'x-twitter' | 'yelp' | 'youtube' | null;
    'linkUrl'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SocialIconSubBlock.TypeEnum"
        },
        {
            "name": "customAssetId",
            "baseName": "custom_asset_id",
            "type": "string"
        },
        {
            "name": "customSrc",
            "baseName": "custom_src",
            "type": "string"
        },
        {
            "name": "customSize",
            "baseName": "custom_size",
            "type": "number"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "linkType",
            "baseName": "link_type",
            "type": "SocialIconSubBlock.LinkTypeEnum"
        },
        {
            "name": "linkUrl",
            "baseName": "link_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SocialIconSubBlock.attributeTypeMap;
    }
}

export namespace SocialIconSubBlock {
    export enum TypeEnum {
        SocialLinkIcon = <any> 'social_link_icon'
    }
    export enum LinkTypeEnum {
        Android = <any> 'android',
        Apple = <any> 'apple',
        Custom = <any> 'custom',
        Discord = <any> 'discord',
        Email = <any> 'email',
        Facebook = <any> 'facebook',
        GooglePlus = <any> 'google-plus',
        Instagram = <any> 'instagram',
        Linkedin = <any> 'linkedin',
        Pinterest = <any> 'pinterest',
        Rss = <any> 'rss',
        Snapchat = <any> 'snapchat',
        Threads = <any> 'threads',
        Tiktok = <any> 'tiktok',
        Twitch = <any> 'twitch',
        Twitter = <any> 'twitter',
        Whatsapp = <any> 'whatsapp',
        XTwitter = <any> 'x-twitter',
        Yelp = <any> 'yelp',
        Youtube = <any> 'youtube'
    }
}
