/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SocialBlockStyles {
    'blockBackgroundColor'?: string | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    /**
    * Text Alignment.
    */
    'iconAlign'?: SocialBlockStyles.IconAlignEnum | 'center' | 'left' | 'right' | null;
    /**
    * Social block icon color.
    */
    'iconColor'?: SocialBlockStyles.IconColorEnum | 'black' | 'default' | 'grey' | 'white' | null;
    /**
    * Social block icon size.
    */
    'iconSize'?: SocialBlockStyles.IconSizeEnum | 'large' | 'medium' | 'small' | null;
    'iconSpacing'?: number | null;
    'labelColor'?: string | null;
    'labelFontFamily'?: string | null;
    'labelFontSize'?: number | null;
    /**
    * Font style.
    */
    'labelFontStyle'?: SocialBlockStyles.LabelFontStyleEnum | 'italic' | 'normal' | null;
    'labelTextDecoration'?: string | null;
    'labelFontWeight'?: string | null;
    'stackOnMobile'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "iconAlign",
            "baseName": "icon_align",
            "type": "SocialBlockStyles.IconAlignEnum"
        },
        {
            "name": "iconColor",
            "baseName": "icon_color",
            "type": "SocialBlockStyles.IconColorEnum"
        },
        {
            "name": "iconSize",
            "baseName": "icon_size",
            "type": "SocialBlockStyles.IconSizeEnum"
        },
        {
            "name": "iconSpacing",
            "baseName": "icon_spacing",
            "type": "number"
        },
        {
            "name": "labelColor",
            "baseName": "label_color",
            "type": "string"
        },
        {
            "name": "labelFontFamily",
            "baseName": "label_font_family",
            "type": "string"
        },
        {
            "name": "labelFontSize",
            "baseName": "label_font_size",
            "type": "number"
        },
        {
            "name": "labelFontStyle",
            "baseName": "label_font_style",
            "type": "SocialBlockStyles.LabelFontStyleEnum"
        },
        {
            "name": "labelTextDecoration",
            "baseName": "label_text_decoration",
            "type": "string"
        },
        {
            "name": "labelFontWeight",
            "baseName": "label_font_weight",
            "type": "string"
        },
        {
            "name": "stackOnMobile",
            "baseName": "stack_on_mobile",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SocialBlockStyles.attributeTypeMap;
    }
}

export namespace SocialBlockStyles {
    export enum IconAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum IconColorEnum {
        Black = <any> 'black',
        Default = <any> 'default',
        Grey = <any> 'grey',
        White = <any> 'white'
    }
    export enum IconSizeEnum {
        Large = <any> 'large',
        Medium = <any> 'medium',
        Small = <any> 'small'
    }
    export enum LabelFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
}
