/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { SocialBlockProperties } from './socialBlockProperties';
import { SocialBlockStyles } from './socialBlockStyles';
export class SocialBlockData {
    'properties': SocialBlockProperties;
    'displayOptions': DisplayOptions;
    'styles': SocialBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "SocialBlockProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "SocialBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return SocialBlockData.attributeTypeMap;
    }
}

