/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { SpacerBlockStyles } from './spacerBlockStyles';
export class SpacerBlockData {
    'displayOptions': DisplayOptions;
    'styles': SpacerBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "SpacerBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return SpacerBlockData.attributeTypeMap;
    }
}

