/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SpamComplaintMethodFilter {
    'field': SpamComplaintMethodFilter.FieldEnum | 'method';
    'method': SpamComplaintMethodFilter.MethodEnum | 'spam_complaint';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "SpamComplaintMethodFilter.FieldEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "SpamComplaintMethodFilter.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return SpamComplaintMethodFilter.attributeTypeMap;
    }
}

export namespace SpamComplaintMethodFilter {
    export enum FieldEnum {
        Method = <any> 'method'
    }
    export enum MethodEnum {
        SpamComplaint = <any> 'spam_complaint'
    }
}
