/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SpinToWinProperties } from './spinToWinProperties';
import { SpinToWinStyles } from './spinToWinStyles';
export class SpinToWin {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'properties': SpinToWinProperties;
    'type': SpinToWin.TypeEnum | 'spin_to_win';
    'styles'?: SpinToWinStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "SpinToWinProperties"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SpinToWin.TypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "SpinToWinStyles"
        }    ];

    static getAttributeTypeMap() {
        return SpinToWin.attributeTypeMap;
    }
}

export namespace SpinToWin {
    export enum TypeEnum {
        SpinToWin = <any> 'spin_to_win'
    }
}
