/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SplitBlockData } from './splitBlockData';
import { SplitBlockV1SubblocksInner } from './splitBlockV1SubblocksInner';
export class SplitBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': SplitBlockV1.ContentTypeEnum | 'block';
    'type': SplitBlockV1.TypeEnum | 'split';
    'data': SplitBlockData;
    'subblocks'?: Array<SplitBlockV1SubblocksInner> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "SplitBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SplitBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "SplitBlockData"
        },
        {
            "name": "subblocks",
            "baseName": "subblocks",
            "type": "Array<SplitBlockV1SubblocksInner>"
        }    ];

    static getAttributeTypeMap() {
        return SplitBlockV1.attributeTypeMap;
    }
}

export namespace SplitBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Split = <any> 'split'
    }
}
