/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SplitBlockV0 {
    'contentType': SplitBlockV0.ContentTypeEnum | 'block';
    'type': SplitBlockV0.TypeEnum | 'split';
    'data': string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "SplitBlockV0.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SplitBlockV0.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SplitBlockV0.attributeTypeMap;
    }
}

export namespace SplitBlockV0 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Split = <any> 'split'
    }
}
