/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class StaticTrackingParam {
    /**
    * The type of the tracking parameter
    */
    'type': StaticTrackingParam.TypeEnum | 'static';
    /**
    * The value of the tracking parameter
    */
    'value': string;
    /**
    * Name of the tracking param
    */
    'name': string;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "StaticTrackingParam.TypeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StaticTrackingParam.attributeTypeMap;
    }
}

export namespace StaticTrackingParam {
    export enum TypeEnum {
        Static = <any> 'static'
    }
}
