/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class StaticReviewBlockProperties {
    'showRating'?: boolean | null;
    'showReviewerName'?: boolean | null;
    'showProductName'?: boolean | null;
    'showVariantName'?: boolean | null;
    'showVerifiedBadge'?: boolean | null;
    'authorPlaceholder'?: string | null;
    'quotePlaceholder'?: string | null;
    'productNamePlaceholder'?: string | null;
    'productVariantNamePlaceholder'?: string | null;
    /**
    * Review block verified badge language.
    */
    'verifiedBadgeLanguage'?: StaticReviewBlockProperties.VerifiedBadgeLanguageEnum | 'dutch' | 'english' | 'french' | 'german' | 'hungarian' | 'italian' | 'japanese' | 'korean' | 'portuguese' | 'spanish' | null;
    'dynamic': boolean | null;
    'author'?: string | null;
    'productName'?: string | null;
    'productVariantName'?: string | null;
    'quote'?: string | null;
    'stars'?: number | null;
    'verified'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "showRating",
            "baseName": "show_rating",
            "type": "boolean"
        },
        {
            "name": "showReviewerName",
            "baseName": "show_reviewer_name",
            "type": "boolean"
        },
        {
            "name": "showProductName",
            "baseName": "show_product_name",
            "type": "boolean"
        },
        {
            "name": "showVariantName",
            "baseName": "show_variant_name",
            "type": "boolean"
        },
        {
            "name": "showVerifiedBadge",
            "baseName": "show_verified_badge",
            "type": "boolean"
        },
        {
            "name": "authorPlaceholder",
            "baseName": "author_placeholder",
            "type": "string"
        },
        {
            "name": "quotePlaceholder",
            "baseName": "quote_placeholder",
            "type": "string"
        },
        {
            "name": "productNamePlaceholder",
            "baseName": "product_name_placeholder",
            "type": "string"
        },
        {
            "name": "productVariantNamePlaceholder",
            "baseName": "product_variant_name_placeholder",
            "type": "string"
        },
        {
            "name": "verifiedBadgeLanguage",
            "baseName": "verified_badge_language",
            "type": "StaticReviewBlockProperties.VerifiedBadgeLanguageEnum"
        },
        {
            "name": "dynamic",
            "baseName": "dynamic",
            "type": "boolean"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "productVariantName",
            "baseName": "product_variant_name",
            "type": "string"
        },
        {
            "name": "quote",
            "baseName": "quote",
            "type": "string"
        },
        {
            "name": "stars",
            "baseName": "stars",
            "type": "number"
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StaticReviewBlockProperties.attributeTypeMap;
    }
}

export namespace StaticReviewBlockProperties {
    export enum VerifiedBadgeLanguageEnum {
        Dutch = <any> 'dutch',
        English = <any> 'english',
        French = <any> 'french',
        German = <any> 'german',
        Hungarian = <any> 'hungarian',
        Italian = <any> 'italian',
        Japanese = <any> 'japanese',
        Korean = <any> 'korean',
        Portuguese = <any> 'portuguese',
        Spanish = <any> 'spanish'
    }
}
