/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class StaticTableBlockProperties {
    'dynamic': boolean | null;
    'numColumns'?: number | null;
    'showHeaders'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dynamic",
            "baseName": "dynamic",
            "type": "boolean"
        },
        {
            "name": "numColumns",
            "baseName": "num_columns",
            "type": "number"
        },
        {
            "name": "showHeaders",
            "baseName": "show_headers",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StaticTableBlockProperties.attributeTypeMap;
    }
}

