/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class StringArrayOperatorStringArrayFilter {
    'type': StringArrayOperatorStringArrayFilter.TypeEnum | 'string';
    /**
    * Operators for string-in-array filters.
    */
    'operator': StringArrayOperatorStringArrayFilter.OperatorEnum | 'in' | 'not-in';
    'value': Array<string>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "StringArrayOperatorStringArrayFilter.TypeEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "StringArrayOperatorStringArrayFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return StringArrayOperatorStringArrayFilter.attributeTypeMap;
    }
}

export namespace StringArrayOperatorStringArrayFilter {
    export enum TypeEnum {
        String = <any> 'string'
    }
    export enum OperatorEnum {
        In = <any> 'in',
        NotIn = <any> 'not-in'
    }
}
