/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StringEnum } from './stringEnum';
export class StringOperatorStringFilter {
    'type': StringEnum | 'string';
    /**
    * Operators for string filters.
    */
    'operator': StringOperatorStringFilter.OperatorEnum | 'contains' | 'ends-with' | 'equals' | 'not-contains' | 'not-ends-with' | 'not-equals' | 'not-starts-with' | 'nregex' | 'regex' | 'starts-with';
    'value': string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "StringEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "StringOperatorStringFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StringOperatorStringFilter.attributeTypeMap;
    }
}

export namespace StringOperatorStringFilter {
    export enum OperatorEnum {
        Contains = <any> 'contains',
        EndsWith = <any> 'ends-with',
        Equals = <any> 'equals',
        NotContains = <any> 'not-contains',
        NotEndsWith = <any> 'not-ends-with',
        NotEquals = <any> 'not-equals',
        NotStartsWith = <any> 'not-starts-with',
        Nregex = <any> 'nregex',
        Regex = <any> 'regex',
        StartsWith = <any> 'starts-with'
    }
}
