/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StringEnum } from './stringEnum';
export class StringPhoneOperatorStringArrayFilter {
    'type': StringEnum | 'string';
    /**
    * Operators for phone string array filters.  Example condition using this filter:         {
    */
    'operator': StringPhoneOperatorStringArrayFilter.OperatorEnum | 'phone-country-code-in' | 'phone-country-code-not-in';
    'value': Array<string>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "StringEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "StringPhoneOperatorStringArrayFilter.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return StringPhoneOperatorStringArrayFilter.attributeTypeMap;
    }
}

export namespace StringPhoneOperatorStringArrayFilter {
    export enum OperatorEnum {
        In = <any> 'phone-country-code-in',
        NotIn = <any> 'phone-country-code-not-in'
    }
}
