/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class SubmitOptInCode {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'submit'?: boolean = true;
    'type': SubmitOptInCode.TypeEnum | 'submit_opt_in_code';
    'properties'?: SubmitOptInCode.PropertiesEnum | 'null';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "submit",
            "baseName": "submit",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SubmitOptInCode.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "SubmitOptInCode.PropertiesEnum"
        }    ];

    static getAttributeTypeMap() {
        return SubmitOptInCode.attributeTypeMap;
    }
}

export namespace SubmitOptInCode {
    export enum TypeEnum {
        SubmitOptInCode = <any> 'submit_opt_in_code'
    }
    export enum PropertiesEnum {
        Null = <any> 'null'
    }
}
