/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscribeViaWhatsAppProperties } from './subscribeViaWhatsAppProperties';
export class SubscribeViaWhatsApp {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'submit'?: boolean = true;
    'type': SubscribeViaWhatsApp.TypeEnum | 'subscribe_via_whatsapp';
    'properties': SubscribeViaWhatsAppProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "submit",
            "baseName": "submit",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscribeViaWhatsApp.TypeEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "SubscribeViaWhatsAppProperties"
        }    ];

    static getAttributeTypeMap() {
        return SubscribeViaWhatsApp.attributeTypeMap;
    }
}

export namespace SubscribeViaWhatsApp {
    export enum TypeEnum {
        SubscribeViaWhatsapp = <any> 'subscribe_via_whatsapp'
    }
}
