/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmailSubscriptionParameters } from './emailSubscriptionParameters';
import { PushSubscriptionParameters } from './pushSubscriptionParameters';
import { SMSSubscriptionParameters } from './sMSSubscriptionParameters';
import { WhatsAppSubscriptionParameters } from './whatsAppSubscriptionParameters';
export class SubscriptionChannels {
    'email'?: EmailSubscriptionParameters;
    'sms'?: SMSSubscriptionParameters;
    'whatsapp'?: WhatsAppSubscriptionParameters;
    'push'?: PushSubscriptionParameters;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "EmailSubscriptionParameters"
        },
        {
            "name": "sms",
            "baseName": "sms",
            "type": "SMSSubscriptionParameters"
        },
        {
            "name": "whatsapp",
            "baseName": "whatsapp",
            "type": "WhatsAppSubscriptionParameters"
        },
        {
            "name": "push",
            "baseName": "push",
            "type": "PushSubscriptionParameters"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionChannels.attributeTypeMap;
    }
}

