/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class TableFallbackHtmlSubBlock {
    'content'?: string | null;
    /**
    * Show on.
    */
    'showOn'?: TableFallbackHtmlSubBlock.ShowOnEnum | 'all' | 'desktop' | 'mobile' | null;
    'id'?: string | null;
    'type': TableFallbackHtmlSubBlock.TypeEnum | 'table_fallback_html';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "showOn",
            "baseName": "show_on",
            "type": "TableFallbackHtmlSubBlock.ShowOnEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TableFallbackHtmlSubBlock.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return TableFallbackHtmlSubBlock.attributeTypeMap;
    }
}

export namespace TableFallbackHtmlSubBlock {
    export enum ShowOnEnum {
        All = <any> 'all',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
    export enum TypeEnum {
        TableFallbackHtml = <any> 'table_fallback_html'
    }
}
