/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class TableFallbackImageSubBlock {
    'dynamic'?: boolean | null;
    'altText'?: string | null;
    'assetId'?: string | null;
    'href'?: string | null;
    'src'?: string | null;
    'width'?: number | null;
    'height'?: number | null;
    'imageWidth'?: number | null;
    /**
    * Image Alignment.
    */
    'imageAlign'?: TableFallbackImageSubBlock.ImageAlignEnum | 'center' | 'left' | 'right' | null;
    /**
    * Show on.
    */
    'showOn'?: TableFallbackImageSubBlock.ShowOnEnum | 'all' | 'desktop' | 'mobile' | null;
    'tableColumnWidth'?: string | null;
    /**
    * Text Alignment.
    */
    'cellTextAlign'?: TableFallbackImageSubBlock.CellTextAlignEnum | 'center' | 'left' | 'right' | null;
    'croppedAssetId'?: string | null;
    'croppedSrc'?: string | null;
    /**
    * Aspect ratio options.
    */
    'croppingAspectRatio'?: TableFallbackImageSubBlock.CroppingAspectRatioEnum | '16:9' | '1:1' | '2:3' | '3:4' | '4:3' | 'circle' | 'custom' | 'original' | null;
    'croppingHeight'?: number | null;
    'croppingWidth'?: number | null;
    'croppingX'?: number | null;
    'croppingY'?: number | null;
    'id'?: string | null;
    'type': TableFallbackImageSubBlock.TypeEnum | 'table_fallback_image';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dynamic",
            "baseName": "dynamic",
            "type": "boolean"
        },
        {
            "name": "altText",
            "baseName": "alt_text",
            "type": "string"
        },
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "src",
            "baseName": "src",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "imageWidth",
            "baseName": "image_width",
            "type": "number"
        },
        {
            "name": "imageAlign",
            "baseName": "image_align",
            "type": "TableFallbackImageSubBlock.ImageAlignEnum"
        },
        {
            "name": "showOn",
            "baseName": "show_on",
            "type": "TableFallbackImageSubBlock.ShowOnEnum"
        },
        {
            "name": "tableColumnWidth",
            "baseName": "table_column_width",
            "type": "string"
        },
        {
            "name": "cellTextAlign",
            "baseName": "cell_text_align",
            "type": "TableFallbackImageSubBlock.CellTextAlignEnum"
        },
        {
            "name": "croppedAssetId",
            "baseName": "cropped_asset_id",
            "type": "string"
        },
        {
            "name": "croppedSrc",
            "baseName": "cropped_src",
            "type": "string"
        },
        {
            "name": "croppingAspectRatio",
            "baseName": "cropping_aspect_ratio",
            "type": "TableFallbackImageSubBlock.CroppingAspectRatioEnum"
        },
        {
            "name": "croppingHeight",
            "baseName": "cropping_height",
            "type": "number"
        },
        {
            "name": "croppingWidth",
            "baseName": "cropping_width",
            "type": "number"
        },
        {
            "name": "croppingX",
            "baseName": "cropping_x",
            "type": "number"
        },
        {
            "name": "croppingY",
            "baseName": "cropping_y",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TableFallbackImageSubBlock.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return TableFallbackImageSubBlock.attributeTypeMap;
    }
}

export namespace TableFallbackImageSubBlock {
    export enum ImageAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum ShowOnEnum {
        All = <any> 'all',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
    export enum CellTextAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum CroppingAspectRatioEnum {
        _169 = <any> '16:9',
        _11 = <any> '1:1',
        _23 = <any> '2:3',
        _34 = <any> '3:4',
        _43 = <any> '4:3',
        Circle = <any> 'circle',
        Custom = <any> 'custom',
        Original = <any> 'original'
    }
    export enum TypeEnum {
        TableFallbackImage = <any> 'table_fallback_image'
    }
}
