/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContentRepeatV1 } from './contentRepeatV1';
import { DynamicTableBlockProperties } from './dynamicTableBlockProperties';
import { StaticTableBlockProperties } from './staticTableBlockProperties';
export type TableBlockDataProperties = StaticTableBlockProperties | DynamicTableBlockProperties;
