/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { TableBlockDataProperties } from './tableBlockDataProperties';
import { TableBlockStyles } from './tableBlockStyles';
export class TableBlockData {
    'properties': TableBlockDataProperties;
    'displayOptions': DisplayOptions;
    'styles': TableBlockStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "TableBlockDataProperties"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "TableBlockStyles"
        }    ];

    static getAttributeTypeMap() {
        return TableBlockData.attributeTypeMap;
    }
}

