/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class TableBlockStyles {
    'blockBackgroundColor'?: string | null;
    'blockBorderColor'?: string | null;
    /**
    * Border style.
    */
    'blockBorderStyle'?: TableBlockStyles.BlockBorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'blockBorderWidth'?: number | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    'cellHorizontalBorderColor'?: string | null;
    /**
    * Border style.
    */
    'cellHorizontalBorderStyle'?: TableBlockStyles.CellHorizontalBorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'cellHorizontalBorderWidth'?: number | null;
    'cellPaddingBottom'?: number | null;
    'cellPaddingLeft'?: number | null;
    'cellPaddingRight'?: number | null;
    'cellPaddingTop'?: number | null;
    /**
    * Vertical alignment.
    */
    'cellVerticalAlign'?: TableBlockStyles.CellVerticalAlignEnum | 'baseline' | 'bottom' | 'middle' | 'top' | null;
    'cellVerticalBorderColor'?: string | null;
    /**
    * Border style.
    */
    'cellVerticalBorderStyle'?: TableBlockStyles.CellVerticalBorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'cellVerticalBorderWidth'?: number | null;
    'headerBackgroundColor'?: string | null;
    'headerFontColor'?: string | null;
    'headerFontFamily'?: string | null;
    'headerFontSize'?: number | null;
    /**
    * Font style.
    */
    'headerFontStyle'?: TableBlockStyles.HeaderFontStyleEnum | 'italic' | 'normal' | null;
    'headerFontWeight'?: string | null;
    'headerLetterSpacing'?: number | null;
    'headerLineHeight'?: number | null;
    'headerPaddingBottom'?: number | null;
    'headerPaddingLeft'?: number | null;
    'headerPaddingRight'?: number | null;
    'headerPaddingTop'?: number | null;
    'headerTextDecoration'?: string | null;
    'tableBackgroundColor'?: string | null;
    'tableFontColor'?: string | null;
    'tableFontFamily'?: string | null;
    'tableFontSize'?: number | null;
    /**
    * Text Alignment.
    */
    'tableTextAlign'?: TableBlockStyles.TableTextAlignEnum | 'center' | 'left' | 'right' | null;
    'useLegacyMobilePadding'?: boolean | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockBorderColor",
            "baseName": "block_border_color",
            "type": "string"
        },
        {
            "name": "blockBorderStyle",
            "baseName": "block_border_style",
            "type": "TableBlockStyles.BlockBorderStyleEnum"
        },
        {
            "name": "blockBorderWidth",
            "baseName": "block_border_width",
            "type": "number"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "cellHorizontalBorderColor",
            "baseName": "cell_horizontal_border_color",
            "type": "string"
        },
        {
            "name": "cellHorizontalBorderStyle",
            "baseName": "cell_horizontal_border_style",
            "type": "TableBlockStyles.CellHorizontalBorderStyleEnum"
        },
        {
            "name": "cellHorizontalBorderWidth",
            "baseName": "cell_horizontal_border_width",
            "type": "number"
        },
        {
            "name": "cellPaddingBottom",
            "baseName": "cell_padding_bottom",
            "type": "number"
        },
        {
            "name": "cellPaddingLeft",
            "baseName": "cell_padding_left",
            "type": "number"
        },
        {
            "name": "cellPaddingRight",
            "baseName": "cell_padding_right",
            "type": "number"
        },
        {
            "name": "cellPaddingTop",
            "baseName": "cell_padding_top",
            "type": "number"
        },
        {
            "name": "cellVerticalAlign",
            "baseName": "cell_vertical_align",
            "type": "TableBlockStyles.CellVerticalAlignEnum"
        },
        {
            "name": "cellVerticalBorderColor",
            "baseName": "cell_vertical_border_color",
            "type": "string"
        },
        {
            "name": "cellVerticalBorderStyle",
            "baseName": "cell_vertical_border_style",
            "type": "TableBlockStyles.CellVerticalBorderStyleEnum"
        },
        {
            "name": "cellVerticalBorderWidth",
            "baseName": "cell_vertical_border_width",
            "type": "number"
        },
        {
            "name": "headerBackgroundColor",
            "baseName": "header_background_color",
            "type": "string"
        },
        {
            "name": "headerFontColor",
            "baseName": "header_font_color",
            "type": "string"
        },
        {
            "name": "headerFontFamily",
            "baseName": "header_font_family",
            "type": "string"
        },
        {
            "name": "headerFontSize",
            "baseName": "header_font_size",
            "type": "number"
        },
        {
            "name": "headerFontStyle",
            "baseName": "header_font_style",
            "type": "TableBlockStyles.HeaderFontStyleEnum"
        },
        {
            "name": "headerFontWeight",
            "baseName": "header_font_weight",
            "type": "string"
        },
        {
            "name": "headerLetterSpacing",
            "baseName": "header_letter_spacing",
            "type": "number"
        },
        {
            "name": "headerLineHeight",
            "baseName": "header_line_height",
            "type": "number"
        },
        {
            "name": "headerPaddingBottom",
            "baseName": "header_padding_bottom",
            "type": "number"
        },
        {
            "name": "headerPaddingLeft",
            "baseName": "header_padding_left",
            "type": "number"
        },
        {
            "name": "headerPaddingRight",
            "baseName": "header_padding_right",
            "type": "number"
        },
        {
            "name": "headerPaddingTop",
            "baseName": "header_padding_top",
            "type": "number"
        },
        {
            "name": "headerTextDecoration",
            "baseName": "header_text_decoration",
            "type": "string"
        },
        {
            "name": "tableBackgroundColor",
            "baseName": "table_background_color",
            "type": "string"
        },
        {
            "name": "tableFontColor",
            "baseName": "table_font_color",
            "type": "string"
        },
        {
            "name": "tableFontFamily",
            "baseName": "table_font_family",
            "type": "string"
        },
        {
            "name": "tableFontSize",
            "baseName": "table_font_size",
            "type": "number"
        },
        {
            "name": "tableTextAlign",
            "baseName": "table_text_align",
            "type": "TableBlockStyles.TableTextAlignEnum"
        },
        {
            "name": "useLegacyMobilePadding",
            "baseName": "use_legacy_mobile_padding",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return TableBlockStyles.attributeTypeMap;
    }
}

export namespace TableBlockStyles {
    export enum BlockBorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum CellHorizontalBorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum CellVerticalAlignEnum {
        Baseline = <any> 'baseline',
        Bottom = <any> 'bottom',
        Middle = <any> 'middle',
        Top = <any> 'top'
    }
    export enum CellVerticalBorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
    export enum HeaderFontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum TableTextAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
}
