/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class TableTextSubBlock {
    'content'?: string | null;
    /**
    * Text Alignment.
    */
    'cellTextAlign'?: TableTextSubBlock.CellTextAlignEnum | 'center' | 'left' | 'right' | null;
    'color'?: string | null;
    'fontFamily'?: string | null;
    'fontSize'?: number | null;
    /**
    * Font style.
    */
    'fontStyle'?: TableTextSubBlock.FontStyleEnum | 'italic' | 'normal' | null;
    'fontWeight'?: string | null;
    'letterSpacing'?: number | null;
    /**
    * Show on.
    */
    'showOn'?: TableTextSubBlock.ShowOnEnum | 'all' | 'desktop' | 'mobile' | null;
    'tableColumnWidth'?: string | null;
    'textDecoration'?: string | null;
    'id'?: string | null;
    'type': TableTextSubBlock.TypeEnum | 'table_text';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "cellTextAlign",
            "baseName": "cell_text_align",
            "type": "TableTextSubBlock.CellTextAlignEnum"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "fontFamily",
            "baseName": "font_family",
            "type": "string"
        },
        {
            "name": "fontSize",
            "baseName": "font_size",
            "type": "number"
        },
        {
            "name": "fontStyle",
            "baseName": "font_style",
            "type": "TableTextSubBlock.FontStyleEnum"
        },
        {
            "name": "fontWeight",
            "baseName": "font_weight",
            "type": "string"
        },
        {
            "name": "letterSpacing",
            "baseName": "letter_spacing",
            "type": "number"
        },
        {
            "name": "showOn",
            "baseName": "show_on",
            "type": "TableTextSubBlock.ShowOnEnum"
        },
        {
            "name": "tableColumnWidth",
            "baseName": "table_column_width",
            "type": "string"
        },
        {
            "name": "textDecoration",
            "baseName": "text_decoration",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TableTextSubBlock.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return TableTextSubBlock.attributeTypeMap;
    }
}

export namespace TableTextSubBlock {
    export enum CellTextAlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum FontStyleEnum {
        Italic = <any> 'italic',
        Normal = <any> 'normal'
    }
    export enum ShowOnEnum {
        All = <any> 'all',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
    export enum TypeEnum {
        TableText = <any> 'table_text'
    }
}
