/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TemplateEnum } from './templateEnum';
import { TemplateUpdateHtmlOrDndQueryResourceObjectAttributes } from './templateUpdateHtmlOrDndQueryResourceObjectAttributes';
export class TemplateUpdateHtmlOrDndQueryResourceObject {
    'type': TemplateEnum | 'template';
    /**
    * The ID of template
    */
    'id': string;
    'attributes': TemplateUpdateHtmlOrDndQueryResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TemplateEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "TemplateUpdateHtmlOrDndQueryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return TemplateUpdateHtmlOrDndQueryResourceObject.attributeTypeMap;
    }
}

export namespace TemplateUpdateHtmlOrDndQueryResourceObject {
}
