/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TextStyleStyles } from './textStyleStyles';
export class TextStyleV1 {
    'id'?: string | null;
    'styleType': TextStyleV1.StyleTypeEnum | 'text-styles';
    'styles': TextStyleStyles;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "styleType",
            "baseName": "style_type",
            "type": "TextStyleV1.StyleTypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "TextStyleStyles"
        }    ];

    static getAttributeTypeMap() {
        return TextStyleV1.attributeTypeMap;
    }
}

export namespace TextStyleV1 {
    export enum StyleTypeEnum {
        TextStyles = <any> 'text-styles'
    }
}
