/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TextBlockDataV1 } from './textBlockDataV1';
export class TextBlockV1 {
    'id'?: string | null;
    'dataId'?: string | null;
    'universalId'?: string | null;
    'contentType': TextBlockV1.ContentTypeEnum | 'block';
    'type': TextBlockV1.TypeEnum | 'text';
    'data': TextBlockDataV1;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataId",
            "baseName": "data_id",
            "type": "string"
        },
        {
            "name": "universalId",
            "baseName": "universal_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "TextBlockV1.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TextBlockV1.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "TextBlockDataV1"
        }    ];

    static getAttributeTypeMap() {
        return TextBlockV1.attributeTypeMap;
    }
}

export namespace TextBlockV1 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Text = <any> 'text'
    }
}
