/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TextProperties } from './textProperties';
import { TextStyles } from './textStyles';
export class Text {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'type': Text.TypeEnum | 'text';
    'styles'?: TextStyles;
    'properties': TextProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Text.TypeEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "TextStyles"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "TextProperties"
        }    ];

    static getAttributeTypeMap() {
        return Text.attributeTypeMap;
    }
}

export namespace Text {
    export enum TypeEnum {
        Text = <any> 'text'
    }
}
