/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DisplayOptions } from './displayOptions';
import { TextBlockStylesV1 } from './textBlockStylesV1';
export class TextBlockDataV1 {
    'content': string;
    'displayOptions': DisplayOptions;
    'styles': TextBlockStylesV1;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "DisplayOptions"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "TextBlockStylesV1"
        }    ];

    static getAttributeTypeMap() {
        return TextBlockDataV1.attributeTypeMap;
    }
}

