/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class UnsupportedSendStrategy {
    'method': UnsupportedSendStrategy.MethodEnum | 'unsupported';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "UnsupportedSendStrategy.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return UnsupportedSendStrategy.attributeTypeMap;
    }
}

export namespace UnsupportedSendStrategy {
    export enum MethodEnum {
        Unsupported = <any> 'unsupported'
    }
}
