/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class VariableTimerConfiguration {
    'type': VariableTimerConfiguration.TypeEnum | 'variable';
    'days': number;
    'hours': number;
    'minutes': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "VariableTimerConfiguration.TypeEnum"
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "number"
        },
        {
            "name": "hours",
            "baseName": "hours",
            "type": "number"
        },
        {
            "name": "minutes",
            "baseName": "minutes",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return VariableTimerConfiguration.attributeTypeMap;
    }
}

export namespace VariableTimerConfiguration {
    export enum TypeEnum {
        Variable = <any> 'variable'
    }
}
