/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class VideoBlockProperties {
    'rawAssetId'?: string | null;
    'srcAssetId'?: string | null;
    'altText'?: string | null;
    'href'?: string | null;
    'overlayToggle'?: boolean | null;
    'rawSrc'?: string | null;
    'src'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rawAssetId",
            "baseName": "raw_asset_id",
            "type": "string"
        },
        {
            "name": "srcAssetId",
            "baseName": "src_asset_id",
            "type": "string"
        },
        {
            "name": "altText",
            "baseName": "alt_text",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "overlayToggle",
            "baseName": "overlay_toggle",
            "type": "boolean"
        },
        {
            "name": "rawSrc",
            "baseName": "raw_src",
            "type": "string"
        },
        {
            "name": "src",
            "baseName": "src",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return VideoBlockProperties.attributeTypeMap;
    }
}

