/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponBlockV0Data } from './couponBlockV0Data';
export class VideoBlockV0 {
    'contentType': VideoBlockV0.ContentTypeEnum | 'block';
    'type': VideoBlockV0.TypeEnum | 'video';
    'data': CouponBlockV0Data | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "VideoBlockV0.ContentTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "VideoBlockV0.TypeEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CouponBlockV0Data"
        }    ];

    static getAttributeTypeMap() {
        return VideoBlockV0.attributeTypeMap;
    }
}

export namespace VideoBlockV0 {
    export enum ContentTypeEnum {
        Block = <any> 'block'
    }
    export enum TypeEnum {
        Video = <any> 'video'
    }
}
