/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class VideoBlockStyles {
    /**
    * Image Alignment.
    */
    'align'?: VideoBlockStyles.AlignEnum | 'center' | 'left' | 'right' | null;
    'backgroundColor'?: string | null;
    'blockBackgroundColor'?: string | null;
    'blockPaddingBottom'?: number | null;
    'blockPaddingLeft'?: number | null;
    'blockPaddingRight'?: number | null;
    'blockPaddingTop'?: number | null;
    'borderColor'?: string | null;
    /**
    * Border style.
    */
    'borderStyle'?: VideoBlockStyles.BorderStyleEnum | 'dashed' | 'dotted' | 'groove' | 'inset' | 'none' | 'outset' | 'ridge' | 'solid' | null;
    'borderWidth'?: number | null;
    'fullWidthMobile'?: boolean | null;
    'height'?: number | null;
    'innerPaddingBottom'?: number | null;
    'innerPaddingLeft'?: number | null;
    'innerPaddingRight'?: number | null;
    'innerPaddingTop'?: number | null;
    'maxWidth'?: number | null;
    'mobileStretchContent'?: boolean | null;
    'width'?: number | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "align",
            "baseName": "align",
            "type": "VideoBlockStyles.AlignEnum"
        },
        {
            "name": "backgroundColor",
            "baseName": "background_color",
            "type": "string"
        },
        {
            "name": "blockBackgroundColor",
            "baseName": "block_background_color",
            "type": "string"
        },
        {
            "name": "blockPaddingBottom",
            "baseName": "block_padding_bottom",
            "type": "number"
        },
        {
            "name": "blockPaddingLeft",
            "baseName": "block_padding_left",
            "type": "number"
        },
        {
            "name": "blockPaddingRight",
            "baseName": "block_padding_right",
            "type": "number"
        },
        {
            "name": "blockPaddingTop",
            "baseName": "block_padding_top",
            "type": "number"
        },
        {
            "name": "borderColor",
            "baseName": "border_color",
            "type": "string"
        },
        {
            "name": "borderStyle",
            "baseName": "border_style",
            "type": "VideoBlockStyles.BorderStyleEnum"
        },
        {
            "name": "borderWidth",
            "baseName": "border_width",
            "type": "number"
        },
        {
            "name": "fullWidthMobile",
            "baseName": "full_width_mobile",
            "type": "boolean"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "innerPaddingBottom",
            "baseName": "inner_padding_bottom",
            "type": "number"
        },
        {
            "name": "innerPaddingLeft",
            "baseName": "inner_padding_left",
            "type": "number"
        },
        {
            "name": "innerPaddingRight",
            "baseName": "inner_padding_right",
            "type": "number"
        },
        {
            "name": "innerPaddingTop",
            "baseName": "inner_padding_top",
            "type": "number"
        },
        {
            "name": "maxWidth",
            "baseName": "max_width",
            "type": "number"
        },
        {
            "name": "mobileStretchContent",
            "baseName": "mobile_stretch_content",
            "type": "boolean"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return VideoBlockStyles.attributeTypeMap;
    }
}

export namespace VideoBlockStyles {
    export enum AlignEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
    export enum BorderStyleEnum {
        Dashed = <any> 'dashed',
        Dotted = <any> 'dotted',
        Groove = <any> 'groove',
        Inset = <any> 'inset',
        None = <any> 'none',
        Outset = <any> 'outset',
        Ridge = <any> 'ridge',
        Solid = <any> 'solid'
    }
}
